import test from "node:test";
import assert from "node:assert/strict";
import { eligible, initialState, selectCooperative, selectWorkerInCooperative } from "../lib/domain.ts";
import { addEvidence, addFeedback, cancelBookingProtected, castVote, createBooking, decideChangeOrder, declineJobSafely, recordOtpIssued, recordOtpVerified, requestChangeOrder, reviewPolicyImpact, reviewPolicySuggestion, settleJob, signIn, signOut, submitPolicySuggestion, transitionJob, updateWorkability } from "../lib/commands.ts";

test("seed covers five services and keeps the worker protection floor",()=>{const state=initialState();assert.equal(state.policy.minimumPayout,760);assert.equal(state.workers.length,5);for(const service of ["electrician","cleaning","appliance","plumbing","carpentry"])assert.ok(state.workers.some(w=>w.skills.includes(service)));});

test("federation selects a cooperative first and that cooperative selects its worker",()=>{const state=initialState(),coop=selectCooperative(state,"electrician");assert.equal(coop?.id,"coop-kharadi");assert.equal(selectWorkerInCooperative(state,coop!.id,"electrician")?.id,"W02");});

test("federation cannot route below worker protection floor",()=>{let state=signIn(initialState(),"customer01","customer");state=createBooking(state,{customerId:"customer01",service:"electrician",locality:"Kharadi",scheduledAt:new Date(0).toISOString(),amount:100});assert.equal(state.jobs[0].amount,760);assert.equal(state.receipts[0].protectedPayout,760);assert.equal(state.jobs[0].cooperativeId,"coop-kharadi");});

test("cross-role lifecycle preserves OTP, proof, Scope Lock and settlement gates",()=>{let state=signIn(initialState(),"customer01","customer");state=createBooking(state,{customerId:"customer01",service:"electrician",locality:"Kharadi",scheduledAt:new Date(0).toISOString()});const jobId=state.jobs[0].id;state=signOut(state);state=signIn(state,"W02","worker");state=transitionJob(state,jobId,"accepted");state=transitionJob(state,jobId,"travelling");state=transitionJob(state,jobId,"arrived");state=signOut(state);state=signIn(state,"customer01","customer");state=recordOtpIssued(state,jobId,{purpose:"start",token:"signed",expiresAt:Date.now()+60000,attemptsLeft:5});state=signOut(state);state=signIn(state,"W02","worker");state=recordOtpVerified(state,jobId,"start");state=addEvidence(state,jobId,"Before/after proof");state=requestChangeOrder(state,jobId,"Extra safe replacement",180);state=signOut(state);state=signIn(state,"customer01","customer");const changeId=state.jobs.find(j=>j.id===jobId)!.changeOrders[0].id;state=decideChangeOrder(state,jobId,changeId,true);assert.equal(state.jobs.find(j=>j.id===jobId)!.amount,940);state=recordOtpIssued(state,jobId,{purpose:"completion",token:"signed2",expiresAt:Date.now()+60000,attemptsLeft:5});state=signOut(state);state=signIn(state,"W02","worker");state=recordOtpVerified(state,jobId,"completion");state=signOut(state);state=signIn(state,"customer01","customer");state=settleJob(state,jobId);state=addFeedback(state,jobId,5,"Completed as agreed");assert.equal(state.jobs.find(j=>j.id===jobId)!.status,"settled");assert.equal(state.settlements[0].workerPayout,940);});

test("completion OTP cannot be issued before work proof",()=>{let state=signIn(initialState(),"customer01","customer");state=createBooking(state,{customerId:"customer01",service:"appliance",locality:"Kharadi",scheduledAt:new Date(0).toISOString()});const jobId=state.jobs[0].id;state=signOut(state);state=signIn(state,"W02","worker");state=transitionJob(state,jobId,"accepted");state=transitionJob(state,jobId,"travelling");state=transitionJob(state,jobId,"arrived");state=signOut(state);state=signIn(state,"customer01","customer");state=recordOtpIssued(state,jobId,{purpose:"start",token:"x",expiresAt:Date.now()+10000,attemptsLeft:5});state=signOut(state);state=signIn(state,"W02","worker");state=recordOtpVerified(state,jobId,"start");state=signOut(state);state=signIn(state,"customer01","customer");assert.throws(()=>recordOtpIssued(state,jobId,{purpose:"completion",token:"x2",expiresAt:Date.now()+10000,attemptsLeft:5}),/work proof/);});

test("structured customer intake persists with the job",()=>{let state=signIn(initialState(),"customer01","customer");state=createBooking(state,{customerId:"customer01",service:"plumbing",locality:"Hadapsar, Pune",scheduledAt:new Date(0).toISOString(),intakeNote:"Tap leaks only when opened",referenceName:"tap.jpg"});assert.equal(state.jobs[0].intakeNote,"Tap leaks only when opened");assert.equal(state.jobs[0].referenceName,"tap.jpg");assert.equal(state.jobs[0].workerId,"W04");});

test("accepted customer cancellation creates worker protection",()=>{let state=signIn(initialState(),"customer01","customer");state=createBooking(state,{customerId:"customer01",service:"cleaning",locality:"Kharadi",scheduledAt:new Date(0).toISOString()});const jobId=state.jobs[0].id;state=signOut(state);state=signIn(state,"W03","worker");state=transitionJob(state,jobId,"accepted");state=signOut(state);state=signIn(state,"customer01","customer");state=cancelBookingProtected(state,jobId,"Plans changed");assert.equal(state.cancellations[0].workerPayout,190);assert.equal(state.cancellations[0].customerRefund,570);});

test("safe worker decline records zero penalty and redispatches without that worker",()=>{let state=signIn(initialState(),"customer01","customer");state=createBooking(state,{customerId:"customer01",service:"electrician",locality:"Kharadi",scheduledAt:new Date(0).toISOString()});const jobId=state.jobs[0].id;state=signOut(state);state=signIn(state,"W02","worker");state=declineJobSafely(state,jobId,"Safety concern");const job=state.jobs.find(j=>j.id===jobId)!;assert.equal(state.safeDeclines[0].penalty,0);assert.equal(state.safeDeclines[0].workerId,"W02");assert.notEqual(job.workerId,"W02");assert.equal(job.workerId,"W01");const latest=state.receipts.find(r=>r.jobId===jobId&&r.workerId==="W01");assert.equal(latest?.protectedPayout,760);});

test("member workability is a hard eligibility input",()=>{let state=initialState();state={...state,workers:state.workers.map(w=>w.id==="W02"?{...w,workloadTodayMinutes:260}:w)};state=signIn(state,"W02","worker");state=updateWorkability(state,{available:true,maxDailyMinutes:240,minRestMinutes:60});assert.equal(eligible(state.workers.find(w=>w.id==="W02")!,"electrician"),false);});

test("worker suggestion can be reviewed without mutating active policy",()=>{let state=signIn(initialState(),"W02","worker");const before=state.policy.version;state=submitPolicySuggestion(state,{category:"safety",title:"More rest after heavy jobs",details:"Heavy jobs should require a longer rest gap before the next offer."});const suggestion=state.suggestions[0];state=signOut(state);state=signIn(state,"admin01","admin");state=reviewPolicySuggestion(state,suggestion.id,"accepted");assert.equal(state.suggestions[0].status,"accepted");assert.equal(state.policy.version,before);});

test("member must review personal policy impact before one-member-one-vote",()=>{let state=signIn(initialState(),"W02","worker");assert.throws(()=>castVote(state,"proposal-floor-860","W02","yes"),/Review your personal policy impact/);state=reviewPolicyImpact(state,"proposal-floor-860","W02");state=castVote(state,"proposal-floor-860","W02","yes");assert.equal(state.votes.length,1);assert.throws(()=>castVote(state,"proposal-floor-860","W02","yes"),/only once/);});
