import test from "node:test";
import assert from "node:assert/strict";
import { eligible, initialState, selectWorkerInCooperative } from "../lib/domain.ts";
import { goldenFederationCapacity, matchFederationCooperative, simulateFederationTwin } from "../lib/federation.ts";
import { addEvidence, addFeedback, activatePolicyProposal, cancelBookingProtected, castVote, createBooking, decideChangeOrder, declineJobSafely, recordOtpIssued, recordOtpVerified, replayFederationDecision, requestChangeOrder, reviewPolicyImpact, reviewPolicySuggestion, settleJob, signIn, signOut, submitPolicySuggestion, transitionJob, updateWorkability, validatePolicyChange } from "../lib/commands.ts";

function bookElectrician(){let state=signIn(initialState(),"customer01","customer");state=createBooking(state,{customerId:"customer01",service:"electrician",locality:"Kharadi, Pune",scheduledAt:new Date(0).toISOString()});return state;}

function settleElectrician(){let state=bookElectrician();const jobId=state.jobs[0].id;state=signOut(state);state=signIn(state,"W02","worker");state=transitionJob(state,jobId,"accepted");state=transitionJob(state,jobId,"travelling");state=transitionJob(state,jobId,"arrived");state=signOut(state);state=signIn(state,"customer01","customer");state=recordOtpIssued(state,jobId,{purpose:"start",token:"signed",expiresAt:Date.now()+60000,attemptsLeft:5});state=signOut(state);state=signIn(state,"W02","worker");state=recordOtpVerified(state,jobId,"start");state=addEvidence(state,jobId,"Before/after proof");state=signOut(state);state=signIn(state,"customer01","customer");state=recordOtpIssued(state,jobId,{purpose:"completion",token:"signed2",expiresAt:Date.now()+60000,attemptsLeft:5});state=signOut(state);state=signIn(state,"W02","worker");state=recordOtpVerified(state,jobId,"completion");state=signOut(state);state=signIn(state,"customer01","customer");return settleJob(state,jobId);}

test("seed covers five services, four cooperatives and the worker protection floor",()=>{const state=initialState();assert.equal(state.policy.minimumPayout,760);assert.equal(state.cooperatives.length,4);assert.ok(state.workers.length>=9);for(const service of ["electrician","cleaning","appliance","plumbing","carpentry"])assert.ok(state.workers.some(w=>w.skills.includes(service)));});

test("home cooperative dispatch happens before federation routing",()=>{const state=bookElectrician();assert.equal(state.jobs[0].homeCooperativeId,"coop-kharadi");assert.equal(state.jobs[0].cooperativeId,"coop-kharadi");assert.equal(state.jobs[0].workerId,"W02");assert.equal(state.jobs[0].federationOpportunityId,undefined);assert.equal(selectWorkerInCooperative(initialState(),"coop-kharadi","electrician")?.id,"W02");});

test("local capacity failure automatically opens protected federation routing",()=>{let state=signIn(initialState(),"customer01","customer");state=createBooking(state,{customerId:"customer01",service:"carpentry",locality:"Kharadi, Pune",scheduledAt:new Date(0).toISOString()});const job=state.jobs[0];assert.equal(job.homeCooperativeId,"coop-kharadi");assert.equal(job.cooperativeId,"coop-yerawada");assert.equal(job.workerId,"W05");assert.ok(job.federationOpportunityId);const opportunity=state.federation.opportunities.find(o=>o.id===job.federationOpportunityId);assert.equal(opportunity?.selectedCooperativeId,"coop-yerawada");assert.equal(opportunity?.workerId,"W05");assert.ok(state.federation.snapshots.some(s=>s.opportunityId===opportunity?.id));});

test("golden federation vector selects cooperative before its worker and explains exclusions",()=>{const state=initialState();const match=matchFederationCooperative({homeCooperativeId:"coop-kharadi",service:"electrician",sla:35,workerPayout:760,capacities:goldenFederationCapacity});assert.equal(match.selectedCooperativeId,"coop-yerawada");assert.match(match.candidates.find(c=>c.cooperativeId==="coop-viman")?.exclusionReason??"",/Workload protection/);assert.equal(match.candidates.find(c=>c.cooperativeId==="coop-hadapsar")?.slaCompatible,false);assert.equal(selectWorkerInCooperative(state,"coop-yerawada","electrician")?.id,"W01");});

test("federation covenant blocks worker-protection undercutting",()=>{const match=matchFederationCooperative({homeCooperativeId:"coop-kharadi",service:"electrician",sla:35,workerPayout:600,capacities:goldenFederationCapacity});assert.equal(match.selectedCooperativeId,null);assert.ok(match.candidates.every(c=>c.protectionCompatible===false));});

test("frozen federation replay reproduces the cooperative decision",()=>{let state=signIn(initialState(),"admin01","admin");const snapshot=state.federation.snapshots[0];state=replayFederationDecision(state,snapshot.id);assert.equal(state.federation.replays[0].status,"confirmed");assert.match(state.federation.replays[0].summary,/Current worker state was not substituted/);});

test("Federation Policy Twin improves coverage without protection violations",()=>{const twin=simulateFederationTwin();assert.ok(twin.mesh.served>twin.localOnly.served);assert.ok(twin.mesh.unfilled<twin.localOnly.unfilled);assert.ok(twin.mesh.crossCooperative>0);assert.equal(twin.mesh.protectionViolations,0);});

test("cross-role lifecycle preserves OTP, proof, Scope Lock and settlement gates",()=>{let state=bookElectrician();const jobId=state.jobs[0].id;state=signOut(state);state=signIn(state,"W02","worker");state=transitionJob(state,jobId,"accepted");state=transitionJob(state,jobId,"travelling");state=transitionJob(state,jobId,"arrived");state=signOut(state);state=signIn(state,"customer01","customer");state=recordOtpIssued(state,jobId,{purpose:"start",token:"signed",expiresAt:Date.now()+60000,attemptsLeft:5});state=signOut(state);state=signIn(state,"W02","worker");state=recordOtpVerified(state,jobId,"start");state=addEvidence(state,jobId,"Before/after proof");state=requestChangeOrder(state,jobId,"Extra safe replacement",180);state=signOut(state);state=signIn(state,"customer01","customer");const changeId=state.jobs.find(j=>j.id===jobId)!.changeOrders[0].id;state=decideChangeOrder(state,jobId,changeId,true);assert.equal(state.jobs.find(j=>j.id===jobId)!.amount,940);state=recordOtpIssued(state,jobId,{purpose:"completion",token:"signed2",expiresAt:Date.now()+60000,attemptsLeft:5});state=signOut(state);state=signIn(state,"W02","worker");state=recordOtpVerified(state,jobId,"completion");state=signOut(state);state=signIn(state,"customer01","customer");state=settleJob(state,jobId);assert.equal(state.jobs.find(j=>j.id===jobId)!.status,"settled");assert.equal(state.settlements[0].workerPayout,940);});

test("completion OTP cannot be issued before work proof",()=>{let state=bookElectrician();const jobId=state.jobs[0].id;state=signOut(state);state=signIn(state,"W02","worker");state=transitionJob(state,jobId,"accepted");state=transitionJob(state,jobId,"travelling");state=transitionJob(state,jobId,"arrived");state=signOut(state);state=signIn(state,"customer01","customer");state=recordOtpIssued(state,jobId,{purpose:"start",token:"x",expiresAt:Date.now()+10000,attemptsLeft:5});state=signOut(state);state=signIn(state,"W02","worker");state=recordOtpVerified(state,jobId,"start");state=signOut(state);state=signIn(state,"customer01","customer");assert.throws(()=>recordOtpIssued(state,jobId,{purpose:"completion",token:"x2",expiresAt:Date.now()+10000,attemptsLeft:5}),/work proof/);});

test("structured customer intake persists with the job",()=>{let state=signIn(initialState(),"customer01","customer");state=createBooking(state,{customerId:"customer01",service:"plumbing",locality:"Hadapsar, Pune",scheduledAt:new Date(0).toISOString(),intakeNote:"Tap leaks only when opened",referenceName:"tap.jpg"});assert.equal(state.jobs[0].intakeNote,"Tap leaks only when opened");assert.equal(state.jobs[0].referenceName,"tap.jpg");assert.equal(state.jobs[0].workerId,"W04");});

test("accepted customer cancellation creates worker protection",()=>{let state=signIn(initialState(),"customer01","customer");state=createBooking(state,{customerId:"customer01",service:"cleaning",locality:"Kharadi",scheduledAt:new Date(0).toISOString()});const jobId=state.jobs[0].id;state=signOut(state);state=signIn(state,"W03","worker");state=transitionJob(state,jobId,"accepted");state=signOut(state);state=signIn(state,"customer01","customer");state=cancelBookingProtected(state,jobId,"Plans changed");assert.equal(state.cancellations[0].workerPayout,190);assert.equal(state.cancellations[0].customerRefund,570);});

test("safe decline records zero penalty, closes one opportunity and redispatches through live federation",()=>{let state=bookElectrician();const jobId=state.jobs[0].id;assert.equal(state.opportunities.find(o=>o.jobId===jobId&&o.workerId==="W02")?.status,"offered");state=signOut(state);state=signIn(state,"W02","worker");state=declineJobSafely(state,jobId,"Safety concern");const job=state.jobs.find(j=>j.id===jobId)!;assert.equal(state.safeDeclines[0].penalty,0);assert.equal(state.opportunities.find(o=>o.jobId===jobId&&o.workerId==="W02")?.status,"declined");assert.ok(job.workerId);assert.ok(job.cooperativeId);assert.notEqual(job.workerId,"W02");assert.notEqual(job.cooperativeId,"coop-kharadi");assert.equal(state.opportunities.find(o=>o.jobId===jobId&&o.workerId===job.workerId)?.status,"offered");const selectedWorker=state.workers.find(w=>w.id===job.workerId);assert.equal(selectedWorker?.cooperativeId,job.cooperativeId);assert.equal(state.receipts.find(r=>r.jobId===jobId&&r.workerId===job.workerId)?.protectedPayout,760);});

test("member workability is a hard eligibility input",()=>{let state=initialState();state={...state,workers:state.workers.map(w=>w.id==="W02"?{...w,workloadTodayMinutes:260}:w)};state=signIn(state,"W02","worker");state=updateWorkability(state,{available:true,maxDailyMinutes:240,minRestMinutes:60});assert.equal(eligible(state.workers.find(w=>w.id==="W02")!,"electrician"),false);});

test("worker suggestion can enter review without mutating the active constitution",()=>{let state=signIn(initialState(),"W02","worker");const before=state.policy.version;state=submitPolicySuggestion(state,{category:"safety",title:"More rest after heavy jobs",details:"Heavy jobs should require a longer rest gap before the next offer."});const suggestion=state.suggestions[0];state=signOut(state);state=signIn(state,"admin01","admin");state=reviewPolicySuggestion(state,suggestion.id,"accepted");assert.equal(state.suggestions[0].status,"accepted");assert.equal(state.policy.version,before);});

test("member must review personal impact before one-member-one-vote",()=>{let state=signIn(initialState(),"W02","worker");assert.throws(()=>castVote(state,"proposal-floor-860","W02","yes"),/Review your personal policy impact/);state=reviewPolicyImpact(state,"proposal-floor-860","W02");state=castVote(state,"proposal-floor-860","W02","yes");assert.equal(state.votes.filter(v=>v.proposalId==="proposal-floor-860").length,9);assert.throws(()=>castVote(state,"proposal-floor-860","W02","yes"),/only once/);});

test("quorum and approval activate a new constitution only for later dispatches",()=>{let state=bookElectrician();const oldReceipt=state.receipts[0];state=signOut(state);state=signIn(state,"W02","worker");state=reviewPolicyImpact(state,"proposal-floor-860","W02");state=castVote(state,"proposal-floor-860","W02","yes");state=signOut(state);state=signIn(state,"admin01","admin");state=activatePolicyProposal(state,"proposal-floor-860");assert.equal(state.policy.version,"constitution-v3");assert.equal(state.policy.minimumPayout,860);assert.equal(oldReceipt.policyVersion,"constitution-v2");assert.equal(state.receipts.find(r=>r.id===oldReceipt.id)?.policyVersion,"constitution-v2");state=signOut(state);state=signIn(state,"customer02","customer");state=createBooking(state,{customerId:"customer02",service:"electrician",locality:"Kharadi",scheduledAt:new Date(1).toISOString()});assert.equal(state.receipts[0].policyVersion,"constitution-v3");assert.equal(state.receipts[0].protectedPayout,860);});

test("protection validator rejects paid priority, reverse auction and floor cuts",()=>{let state=initialState();assert.equal(validatePolicyChange(state,{minimumPayout:760,maxAddedWaitMinutes:12,paidPriority:true}).valid,false);assert.equal(validatePolicyChange(state,{minimumPayout:760,maxAddedWaitMinutes:12,reverseAuction:true}).valid,false);assert.equal(validatePolicyChange(state,{minimumPayout:700,maxAddedWaitMinutes:12}).valid,false);});

test("low rating enters human review and never deactivates the worker",()=>{let state=settleElectrician();const job=state.jobs[0];const workerBefore=state.workers.find(w=>w.id===job.workerId)!;state=addFeedback(state,job.id,1,"Service outcome needs review");const workerAfter=state.workers.find(w=>w.id===job.workerId)!;assert.equal(workerBefore.active,true);assert.equal(workerAfter.active,true);assert.ok(state.issues.some(i=>i.jobId===job.id&&i.category==="Low rating review"&&i.status==="open"));});
