import test from "node:test";
import assert from "node:assert/strict";
import { initialState } from "../lib/domain.ts";
import type { AppState } from "../lib/domain.ts";
import { createBooking, settleJob, signIn } from "../lib/commands.ts";
import { approvedInvoice } from "../lib/payments.ts";
import { attachTestInvoice, recordTestCapture, invoiceScope } from "../lib/payment-commands.ts";
import { summarizeWorkerEarnings } from "../lib/earnings.ts";
function completed():AppState{const s=createBooking(signIn(initialState(),"customer01","customer"),{customerId:"customer01",service:"electrician",locality:"Kharadi",scheduledAt:new Date().toISOString()});return{...s,jobs:s.jobs.map(j=>({...j,status:"completed" as const}))};}
test("test capture imports only the frozen server invoice, credits the correct member once and excludes local double settlement",()=>{let s=completed(),job=s.jobs[0];const invoice=approvedInvoice({jobId:job.id,workerId:job.workerId,receiptId:job.receiptId,scope:invoiceScope(job),amount:job.amount,protectionFloor:760});const base=summarizeWorkerEarnings(s,"W02").total;s=attachTestInvoice(signIn(s,"admin01","admin"),job.id,invoice,invoice.token);assert.throws(()=>settleJob(signIn(s,"customer01","customer"),job.id),/Razorpay/);assert.throws(()=>recordTestCapture(s,job.id,invoice),/Verified captured/);const captured={...invoice,status:"captured" as const,orderId:"order_123",paymentId:"pay_123",capturedAt:new Date().toISOString()};assert.throws(()=>recordTestCapture(s,job.id,{...captured,total:75000}),/Verified captured/);s=recordTestCapture(s,job.id,captured);assert.equal(s.settlements.length,1);assert.equal(s.settlements[0].mode,"razorpay-test");assert.equal(summarizeWorkerEarnings(s,"W02").total,base+760);const again=recordTestCapture(s,job.id,captured);assert.equal(again,s);assert.equal(again.settlements.length,1);assert.equal(summarizeWorkerEarnings(s,"W01").total,summarizeWorkerEarnings(initialState(),"W01").total);});
test("public customer or unrelated member cannot approve or import another customer's test invoice",()=>{let s=completed(),job=s.jobs[0];const invoice=approvedInvoice({jobId:job.id,workerId:job.workerId,receiptId:job.receiptId,scope:invoiceScope(job),amount:760,protectionFloor:760});assert.throws(()=>attachTestInvoice(s,job.id,invoice,invoice.token),/admin/);s=attachTestInvoice(signIn(s,"admin01","admin"),job.id,invoice,invoice.token);const captured={...invoice,status:"captured" as const,orderId:"order_123",paymentId:"pay_123",capturedAt:new Date().toISOString()};assert.throws(()=>recordTestCapture(signIn(s,"another-customer","customer"),job.id,captured),/customer or cooperative/);assert.throws(()=>recordTestCapture(signIn(s,"W02","worker"),job.id,captured),/customer or cooperative/);});
test("invoice approval freezes approved scope and the zero-commission split, excluding refused changes",()=>{let s=completed();s={...s,jobs:s.jobs.map(j=>({...j,amount:940,changeOrders:[{id:"extra-approved",description:"Replace seal with customer consent",amountDelta:180,requestedBy:j.workerId!,approved:true},{id:"extra-refused",description:"Replace entire tap",amountDelta:2000,requestedBy:j.workerId!,approved:false}]}))};const job=s.jobs[0],scope=invoiceScope(job),invoice=approvedInvoice({jobId:job.id,workerId:job.workerId,receiptId:job.receiptId,scope,amount:940,protectionFloor:760});assert.match(scope,/extra-approved/);assert.doesNotMatch(scope,/extra-refused/);s=signIn(s,"admin01","admin");assert.throws(()=>attachTestInvoice(s,job.id,{...invoice,scope:job.service},invoice.token),/differs/);assert.throws(()=>attachTestInvoice(s,job.id,{...invoice,worker:90000,commission:4000},invoice.token),/differs/);s=attachTestInvoice(s,job.id,invoice,invoice.token);const captured={...invoice,status:"captured" as const,orderId:"order_123",paymentId:"pay_123",capturedAt:new Date().toISOString()};assert.throws(()=>recordTestCapture(s,job.id,{...captured,scope:"Different repair"}),/Verified captured/);s=recordTestCapture(s,job.id,captured);assert.equal(s.settlements[0].workerPayout,940);assert.throws(()=>recordTestCapture(signIn(s,"W01","worker"),job.id,captured),/customer or cooperative/);});
