import test from "node:test";
import assert from "node:assert/strict";
import { createHmac } from "node:crypto";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { SqlitePaymentRepository } from "../lib/payment-repository.ts";
import { TestPaymentService, approvedInvoice, verifySignature, type GatewayTransport } from "../lib/payments.ts";
const input={jobId:"KMS-00001",workerId:"W02",receiptId:"KMS-00001-receipt",scope:"Repair switch",amount:760,protectionFloor:760};
function setup(){const repo=new SqlitePaymentRepository(":memory:");let amount=76000,status="captured",orderCalls=0,transferCalls=0;const gateway:GatewayTransport={async call(path,method,body){if(path==="orders"){orderCalls++;return{id:"order_123",amount:76000,currency:"INR",receipt:(body as {receipt:string}).receipt};}if(path==="orders/order_123")return{id:"order_123",amount:76000,currency:"INR",receipt:repo.forJob(input.jobId)!.id};if(path.endsWith("/transfers")){transferCalls++;return {items:[{id:"trf_123"}]};}if(path.startsWith("transfers/"))return{id:"trf_123",source:"pay_123",recipient:"acc_123",amount:76000,currency:"INR",status:"processed"};return {id:"pay_123",order_id:"order_123",amount,currency:"INR",status};}};const service=new TestPaymentService(repo,gateway,"test-secret");return{repo,service,counts:()=>({orderCalls,transferCalls}),setPayment:(a:number,s:string)=>{amount=a;status=s;}};}
const signature=createHmac("sha256","test-secret").update("order_123|pay_123").digest("hex");
test("approved server invoices freeze amount, recipient and commission; client cannot lower the floor",()=>{const x=setup(),i=x.service.approve(input);assert.equal(i.worker,76000);assert.equal(i.commission,0);assert.throws(()=>x.service.approve({...input,amount:860}),/frozen/);for(const amount of [759,NaN,Infinity,0,760.5])assert.throws(()=>approvedInvoice({...input,amount}));assert.throws(()=>x.service.authenticate(i.id,"wrong"),/denied/);x.repo.close();});
test("order retries reuse one order and reject concurrent duplicate creation",async()=>{const x=setup(),i=x.service.approve(input);const results=await Promise.allSettled([x.service.order(i.id,i.token),x.service.order(i.id,i.token)]);assert.equal(results.filter(r=>r.status==="fulfilled").length,1);assert.equal((await x.service.order(i.id,i.token)).orderId,"order_123");assert.equal(x.counts().orderCalls,1);x.repo.close();});
test("checkout signature and exact provider capture are required; callback/webhook duplicates post once",async()=>{const x=setup(),i=x.service.approve(input);await x.service.order(i.id,i.token);await assert.rejects(()=>x.service.confirm(i.id,i.token,"pay_123","wrong"),/signature/);x.setPayment(76000,"authorized");await assert.rejects(()=>x.service.confirm(i.id,i.token,"pay_123",signature),/not captured/);x.setPayment(75000,"captured");await assert.rejects(()=>x.service.confirm(i.id,i.token,"pay_123",signature),/exact invoice/);assert.equal(x.repo.find(i.id)?.status,"ordered");x.setPayment(76000,"captured");const c=await x.service.confirm(i.id,i.token,"pay_123",signature);assert.equal(c.status,"captured");assert.deepEqual(await x.service.capture(c,"pay_123","webhook-event-1"),c);assert.deepEqual(await x.service.confirm(i.id,i.token,"pay_123",signature),c);assert.throws(()=>x.repo.capture(i.id,"pay_different"),/different payment/);x.repo.close();});
test("worker Route transfers are separate, captured-only, duplicate protected and reconciled",async()=>{const x=setup(),i=x.service.approve(input);await assert.rejects(()=>x.service.transfer(i.id,"acc_123"),/Captured/);await x.service.order(i.id,i.token);await x.service.confirm(i.id,i.token,"pay_123",signature);const t=await x.service.transfer(i.id,"acc_123");assert.equal(t.transfer?.status,"created");assert.equal(t.transfer?.amount,76000);await assert.rejects(()=>x.service.transfer(i.id,"acc_123"),/twice/);assert.equal(x.counts().transferCalls,1);const verified=await x.service.reconcileTransfer(i.id,"trf_123");assert.equal(verified.transfer?.status,"processed");x.repo.close();});
test("ambiguous provider errors freeze retries until the operator reconciles an order",async()=>{const x=setup(),i=x.service.approve(input);const failing=new TestPaymentService(x.repo,{async call(){throw new Error("connection lost after possible provider acceptance");}},"test-secret");await assert.rejects(()=>failing.order(i.id,i.token));assert.equal(x.repo.find(i.id)?.status,"order-review");await assert.rejects(()=>x.service.order(i.id,i.token),/reconciliation/);await x.service.reconcileOrder(i.id,"order_123");assert.equal((await x.service.order(i.id,i.token)).orderId,"order_123");assert.equal(x.counts().orderCalls,0);x.repo.close();});
test("SQLite invoices and captured ledger survive process/database reopen",async()=>{const dir=mkdtempSync(join(tmpdir(),"kaamsabha-payment-")),path=join(dir,"test.sqlite");try{let repo=new SqlitePaymentRepository(path),i=approvedInvoice(input);repo.create(i);repo.claim(i.id,"approved","ordered");i={...repo.find(i.id)!,orderId:"order_123"};repo.save(i);repo.capture(i.id,"pay_123");repo.close();repo=new SqlitePaymentRepository(path);assert.equal(repo.forJob(input.jobId)?.paymentId,"pay_123");assert.equal(repo.forOrder("order_123")?.status,"captured");assert.equal(repo.capture(i.id,"pay_123").status,"captured");repo.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test("webhook HMAC authenticates the exact raw body, independent of checkout secret",()=>{const raw='{"event":"payment.captured"}',sig=createHmac("sha256","webhook-only").update(raw).digest("hex");assert.equal(verifySignature(raw,sig,"webhook-only"),true);assert.equal(verifySignature(raw+" ",sig,"webhook-only"),false);assert.equal(verifySignature(raw,sig,"test-secret"),false);});

test("a valid signature for an authorized payment can be reconciled after later capture without a webhook",async()=>{const x=setup(),i=x.service.approve(input);await x.service.order(i.id,i.token);x.setPayment(76000,"authorized");await assert.rejects(()=>x.service.confirm(i.id,i.token,"pay_123",signature),/not captured/);assert.equal(x.repo.find(i.id)?.pendingPaymentId,"pay_123");x.setPayment(76000,"captured");assert.equal((await x.service.read(i.id,i.token)).status,"captured");x.repo.close();});

test("repository prevents invoice edits and capture rollback; provider reversals remain visible",async()=>{const x=setup(),i=x.service.approve(input);assert.throws(()=>x.repo.save({...i,total:75000}),/immutable/);await x.service.order(i.id,i.token);const captured=await x.service.confirm(i.id,i.token,"pay_123",signature);assert.throws(()=>x.repo.save({...captured,status:"approved"}),/reset/);await x.service.transfer(i.id,"acc_123");const review=new TestPaymentService(x.repo,{async call(){return {source:"pay_123",recipient:"acc_123",amount:76000,currency:"INR",status:"partially_reversed",amount_reversed:10000,settlement_status:"pending",fees:100,tax:18};}},"test-secret");const reconciled=await review.reconcileTransfer(i.id,"trf_123");assert.equal(reconciled.transfer?.status,"partially_reversed");assert.equal(reconciled.transfer?.amountReversed,10000);assert.equal(reconciled.transfer?.settlementStatus,"pending");assert.equal(reconciled.transfer?.providerFees,100);x.repo.close();});
