import test from "node:test";
import assert from "node:assert/strict";
import { initialState } from "../lib/domain.ts";
import { addWorkProof, approveEmergencyReplacement, cancelBookingProtected, createBooking, decideChangeOrder, declineJobSafely, openChallenge, replayChallenge, interruptJobForEmergency, recordOtpIssued, recordOtpVerified, reportJobConcern, requestChangeOrder, reviewInterruptedPay, settleJob, signIn, transitionJob } from "../lib/commands.ts";
import { decidePreStartScopeChange, proposePreStartScopeChange } from "../lib/prestart-scope.ts";
import { jobFlow } from "../lib/job-flow.ts";
import { workerNextAction } from "../lib/worker-guidance.ts";
import { adminOverview } from "../lib/admin-overview.ts";
import { proofInput } from "../lib/proof-input.ts";
function booked(){return createBooking(signIn(initialState(),"customer01","customer"),{customerId:"customer01",service:"plumbing",locality:"Kharadi",scheduledAt:new Date().toISOString(),intakeNote:"Fix leaking tap without replacing it unless approved"});}
function arrived(){let s=booked();s=signIn(s,"W13","worker");for(const status of ["accepted","travelling","arrived"] as const)s=transitionJob(s,s.jobs[0].id,status);return s;}
function started(){let s=arrived();s=signIn(s,"customer01","customer");s=recordOtpIssued(s,s.jobs[0].id,{purpose:"start",token:"unit-only",expiresAt:Date.now()+60000,attemptsLeft:5});s=recordOtpVerified(signIn(s,"W13","worker"),s.jobs[0].id,"start");return s;}
test("emergency releases the only live offer; replacement is customer-approved and frozen",()=>{
  let s=started(),original=JSON.stringify(s.receipts[0]),jobId=s.jobs[0].id;
  s=addWorkProof(s,jobId,{phase:"after",explanation:"Isolated water before leaving",checksDone:"Water supply is off",partsUsed:"None"});
  s=interruptJobForEmergency(s,jobId,"Family emergency","Replace washer and test tap");
  assert.equal(s.jobs[0].workerId,undefined);assert.equal(s.jobs[0].startOtp,undefined);assert.equal(s.opportunities[0].status,"released");assert.equal(s.workers.find(w=>w.id==="W13")?.available,false);assert.equal(s.workers.find(w=>w.id==="W13")?.rating,4.9);assert.equal(jobFlow(s.jobs[0],"customer").waitingOn,"customer");assert.equal(adminOverview(s).waitingJobs,0);assert.equal(adminOverview(s).replacementApprovals,1);
  assert.throws(()=>transitionJob(s,jobId,"accepted"),/assigned/);
  assert.throws(()=>approveEmergencyReplacement(s,jobId),/customer session/);
  s=approveEmergencyReplacement(signIn(s,"customer01","customer"),jobId);
  assert.equal(s.jobs[0].workerId,"W12");assert.equal(s.opportunities.filter(o=>o.jobId===jobId&&o.status==="offered").length,1);assert.equal(JSON.stringify(s.receipts.find(r=>r.id===s.jobs[0].handoverHistory![0].fromReceiptId)),original);
  assert.throws(()=>approveEmergencyReplacement(s,jobId),/not awaiting/);assert.equal(s.jobs.length,1);
  s=signIn(s,"W12","worker");for(const status of ["accepted","travelling","arrived"] as const)s=transitionJob(s,jobId,status);
  s=recordOtpIssued(signIn(s,"customer01","customer"),jobId,{purpose:"start",token:"new-start",expiresAt:Date.now()+60000,attemptsLeft:5});s=recordOtpVerified(signIn(s,"W12","worker"),jobId,"start");
  assert.equal(workerNextAction(s.jobs[0]),"proof");assert.throws(()=>recordOtpIssued(signIn(s,"customer01","customer"),jobId,{purpose:"completion",token:"bad",expiresAt:Date.now()+60000,attemptsLeft:5}),/current member/);
  s=addWorkProof(s,jobId,{phase:"after",explanation:"Replaced washer and reconnected tap",checksDone:"Ran water, no visible drip",partsUsed:"Washer"});s=recordOtpIssued(signIn(s,"customer01","customer"),jobId,{purpose:"completion",token:"finish",expiresAt:Date.now()+60000,attemptsLeft:5});s=recordOtpVerified(signIn(s,"W12","worker"),jobId,"completion");s=signIn(s,"customer01","customer");
  assert.throws(()=>settleJob(s,jobId),/pay review/);s=reviewInterruptedPay(signIn(s,"admin01","admin"),jobId,s.jobs[0].handoverHistory![0].id,"Cooperative reviews 20 minutes of work; separate welfare funding approval pending, no customer surcharge.");s=settleJob(signIn(s,"customer01","customer"),jobId);assert.equal(s.settlements[0].workerId,"W12");assert.equal(s.settlements[0].workerPayout,760);
});
test("no safe replacement stays unassigned and repeat capacity checks never create an extra offer",()=>{let s=interruptJobForEmergency(arrived(),arrived().jobs[0].id,"Health emergency","Fix tap");s={...s,workers:s.workers.map(w=>({...w,available:false}))};s=signIn(s,"customer01","customer");s=approveEmergencyReplacement(s,s.jobs[0].id);s=approveEmergencyReplacement(s,s.jobs[0].id);assert.equal(s.jobs[0].status,"requested");assert.equal(s.jobs[0].handoverHistory![0].status,"awaiting-capacity");assert.equal(s.opportunities.filter(o=>o.status==="offered").length,0);});
test("before photo alone cannot finish work; scope pending invalidates the finish code",()=>{let s=arrived();s=addWorkProof(s,s.jobs[0].id,{phase:"before",explanation:"Visible drip from tap"});assert.throws(()=>addWorkProof(s,s.jobs[0].id,{phase:"after",explanation:"Done",checksDone:"Tested"}),/during work/);s=started();s=addWorkProof(s,s.jobs[0].id,{phase:"after",explanation:"Tightened seal",checksDone:"Checked drip",partsUsed:"None"});s=recordOtpIssued(signIn(s,"customer01","customer"),s.jobs[0].id,{purpose:"completion",token:"finish",expiresAt:Date.now()+60000,attemptsLeft:5});s=requestChangeOrder(signIn(s,"W13","worker"),s.jobs[0].id,"Replace washer with customer consent",100);assert.equal(s.jobs[0].completionOtp,undefined);assert.equal(proofInput(s.jobs[0]).approvedChanges.length,0);assert.throws(()=>recordOtpVerified(s,s.jobs[0].id,"completion"),/not issued/);});
test("later rules cannot inflate an old quote, goodwill, cancellation or settlement",()=>{let s=arrived(),jobId=s.jobs[0].id;s={...s,policy:{...s.policy,minimumPayout:860,version:"constitution-v3"}};s=proposePreStartScopeChange(s,jobId,"Help tighten the handle for free",0);s=decidePreStartScopeChange(signIn(s,"customer01","customer"),jobId,s.jobs[0].changeOrders[0].id,true);assert.equal(s.jobs[0].amount,760);
  let active=started();active={...active,policy:{...active.policy,minimumPayout:860}};active=requestChangeOrder(active,active.jobs[0].id,"Free handle adjustment",0);active=decideChangeOrder(signIn(active,"customer01","customer"),active.jobs[0].id,active.jobs[0].changeOrders[0].id,true);assert.equal(active.jobs[0].amount,760);
  let c=transitionJob(signIn(booked(),"W13","worker"),booked().jobs[0].id,"accepted");c={...c,policy:{...c.policy,minimumPayout:860}};c=cancelBookingProtected(signIn(c,"customer01","customer"),c.jobs[0].id,"No longer needed");assert.equal(c.cancellations[0].workerPayout,190);assert.equal(c.cancellations[0].customerRefund,570);
  active={...active,jobs:active.jobs.map(j=>({...j,status:"completed"}))};active=settleJob(active,active.jobs[0].id);assert.equal(active.settlements[0].amount,active.settlements[0].workerPayout);assert.equal(active.settlements[0].workerPayout,760);
});
test("safety reports are job-linked, human-reviewed and unavailable to unrelated accounts",()=>{let s=booked();assert.throws(()=>reportJobConcern(signIn(s,"W02","worker"),s.jobs[0].id,"Safety concern","Customer locked the door"),/participants/);s=reportJobConcern(s,s.jobs[0].id,"Unapproved helper","Second person arrived without approval");assert.equal(s.issues[0].jobId,s.jobs[0].id);assert.match(s.issues[0].notes[1],/receipt/);assert.deepEqual(s.workers,booked().workers);assert.equal(s.jobs[0].amount,760);});
test("quotes and scope reject non-finite numbers",()=>{const s=signIn(initialState(),"customer01","customer");for(const amount of [NaN,Infinity,-1])assert.throws(()=>createBooking(s,{customerId:"customer01",service:"plumbing",locality:"Kharadi",scheduledAt:"now",amount}),/valid/);for(const amount of [NaN,Infinity,-1])assert.throws(()=>requestChangeOrder(started(),started().jobs[0].id,"Extra parts",amount),/non-negative/);});

test("a later floor needs customer consent on redispatch, and replay excludes the member who declined",()=>{let s=signIn(booked(),"W13","worker"),jobId=s.jobs[0].id,old=JSON.stringify(s.receipts[0]);s={...s,policy:{...s.policy,minimumPayout:860,version:"constitution-v3"},cooperatives:s.cooperatives.map(c=>({...c,policyVersion:"constitution-v3"}))};s=declineJobSafely(s,jobId,"Schedule conflict");assert.equal(s.jobs[0].workerId,undefined);assert.equal(s.jobs[0].amount,760);assert.equal(s.workers.find(w=>w.id==="W13")?.available,true);s=approveEmergencyReplacement(signIn(s,"customer01","customer"),jobId);assert.equal(s.jobs[0].workerId,"W12");assert.equal(s.jobs[0].amount,860);assert.equal(s.receipts[0].protectedPayout,860);assert.equal(JSON.stringify(s.receipts.find(r=>r.id===s.jobs[0].handoverHistory![0].fromReceiptId)),old);s=openChallenge(signIn(s,"W12","worker"),jobId,{receiptId:s.jobs[0].receiptId,category:"opportunity",statement:"Check this replacement decision",desiredOutcome:"Explain why"});s=replayChallenge(signIn(s,"admin01","admin"),s.challenges[0].id);assert.equal(s.challenges[0].replayResult?.outcome,"confirmed");assert.equal(s.challenges[0].replayResult?.expectedWorkerId,"W12");});
