"use client";

import { useEffect, useMemo, useState } from "react";
import { createBooking, openIssue, signIn, signOut, transitionJob } from "@/lib/commands";
import { AppState, initialState, Locale, Role } from "@/lib/domain";
import { stateRepository } from "@/lib/repository";
import { copy } from "@/lib/i18n";

const roles: { id: Role; title: string; note: string; demo: string }[] = [
  { id: "customer", title: "Customer", note: "Find, book and track trusted local services", demo: "customer01" },
  { id: "worker", title: "Worker member", note: "See tasks, payout and fair-work reasons", demo: "W02" },
  { id: "admin", title: "Cooperative admin", note: "Run operations, rules and member governance", demo: "admin01" }
];
const services = [
  { id: "electrician", name: "Electrical", icon: "⚡", note: "Repairs, fittings & safety", eta: "22 min" },
  { id: "cleaning", name: "Home cleaning", icon: "✦", note: "Rooms, kitchen & deep clean", eta: "18 min" },
  { id: "appliance", name: "Appliance repair", icon: "⌁", note: "Diagnosis & repair visit", eta: "28 min" }
];
const labels: Record<string,string> = { requested:"Finding a member", assigned:"Worker assigned", accepted:"Accepted", travelling:"On the way", arrived:"Arrived", started:"Work in progress", change_pending:"Change approval", completed:"Work completed", settled:"Paid & settled", cancelled:"Cancelled" };

export default function Home() {
  const [state, setState] = useState<AppState>(initialState());
  const [ready, setReady] = useState(false);
  const [error, setError] = useState("");
  const [tab, setTab] = useState("home");
  useEffect(() => { setState(stateRepository.load()); setReady(true); }, []);
  useEffect(() => { if (ready) stateRepository.save(state); }, [state, ready]);
  const t = copy[state.locale];
  const worker = state.session?.role === "worker" ? state.workers.find(w => w.id === state.session?.userId || w.name.toLowerCase().includes(state.session?.userId.toLowerCase() || "")) : undefined;
  const visibleJobs = useMemo(() => state.session?.role === "customer" ? state.jobs.filter(j => j.customerId === state.session?.userId) : state.session?.role === "worker" ? state.jobs.filter(j => j.workerId === worker?.id) : state.jobs, [state.jobs, state.session, worker]);
  const currentJob = visibleJobs.find(j => !["settled","cancelled"].includes(j.status)) || visibleJobs[0];
  const receipt = currentJob ? state.receipts.find(r => r.jobId === currentJob.id) : undefined;
  const run = (fn: () => AppState) => { try { setError(""); setState(fn()); } catch (e) { setError(e instanceof Error ? e.message : "Action failed"); } };
  const setLocale = (locale: Locale) => setState(s => ({...s, locale, revision:s.revision+1}));
  if (!ready) return <main className="shell loading">Loading KaamSabha…</main>;

  if (!state.session) return <main className="authShell"><section className="authCard">
    <div className="authIntro"><span className="brandMark">K</span><p className="eyebrow">SIH26089 · Cooperative services</p><h1>Reliable local help.<br/>Fair work behind it.</h1><p>Book household and community services from verified worker-members. Allocation follows cooperative rules—not bidding wars.</p><div className="trustRow"><span>✓ Verified members</span><span>✓ Protected pay</span><span>✓ Decision receipts</span></div></div>
    <form className="rolePicker" onSubmit={(e) => { e.preventDefault(); const data = new FormData(e.currentTarget); run(() => signIn(state, String(data.get("userId")), String(data.get("role")) as Role)); }}>
      <h2>Enter demo</h2><p>Choose the view a judge wants to inspect.</p>{roles.map((r,i)=><label className="roleChoice" key={r.id}><input type="radio" name="role" value={r.id} defaultChecked={i===0} onChange={(e)=>{ const f=e.currentTarget.form; const input=f?.elements.namedItem("userId") as HTMLInputElement; if(input) input.value=r.demo; }}/><span><strong>{r.title}</strong><small>{r.note}</small></span></label>)}
      <label className="field">Demo ID<input name="userId" defaultValue="customer01" autoComplete="username" /></label><button type="submit">Open workspace →</button>{error && <p role="alert" className="error">{error}</p>}
    </form>
  </section></main>;

  const role = state.session.role;
  const title = role === "customer" ? "What do you need help with?" : role === "worker" ? `${worker?.name || "Member"}, here’s your work` : "Cooperative control room";
  return <main className="shell">
    <header className="topbar"><div className="brand"><span className="brandMark small">K</span><div><strong>KaamSabha</strong><small>Worker-owned services</small></div></div><div className="topActions"><label className="locale"><span className="srOnly">{t.language}</span><select value={state.locale} onChange={e=>setLocale(e.target.value as Locale)}><option value="en">EN</option><option value="hi">हिं</option><option value="mr">मर</option></select></label><button className="ghost" onClick={() => run(() => signOut(state))}>{t.logout}</button></div></header>
    <div className="appGrid"><aside className="sideNav"><div className="identity"><span className={`roleDot ${role}`}></span><div><strong>{role === "worker" ? worker?.name : state.session.userId}</strong><small>{roles.find(r=>r.id===role)?.title}</small></div></div><nav aria-label="Primary">{(role === "customer" ? [["home",t.home],["orders",t.orders],["support","Help & issues"]] : role === "worker" ? [["home",t.current],["fair",t.fair],["earnings","Earnings"],["governance",t.governance]] : [["home",t.operations],["workers","Workers"],["issues","Issues"],["settlements","Settlements"],["governance",t.governance],["demand",t.demand],["federation","Federation"]]).map(([id,label])=><button key={id} className={tab===id?"navItem active":"navItem"} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className="constitution"><small>ACTIVE CONSTITUTION</small><strong>{state.policy.version}</strong><span>₹{state.policy.minimumPayout} protection floor</span></div></aside>
      <section className="workspace"><div className="pageHead"><div><p className="eyebrow">Shared cooperative register · rev {state.revision}</p><h1>{title}</h1></div>{role === "admin" && <span className="statusChip">● Demo state healthy</span>}</div>
        {role === "customer" && tab === "home" && <CustomerHome state={state} run={run} />}
        {role === "customer" && tab === "orders" && <Orders jobs={visibleJobs} />}
        {role === "customer" && tab === "support" && <Support currentJob={currentJob} onIssue={(c)=>run(()=>openIssue(state,state.session!.userId,c,currentJob?.id))} />}
        {role === "worker" && tab === "home" && <WorkerHome state={state} job={currentJob} receipt={receipt} run={run} worker={worker} />}
        {role === "worker" && tab === "fair" && <FairWork state={state} receipt={receipt} worker={worker} />}
        {role === "worker" && tab === "earnings" && <Earnings jobs={visibleJobs} />}
        {role === "worker" && tab === "governance" && <Governance state={state} />}
        {role === "admin" && <AdminView state={state} tab={tab} />}
        {error && <p role="alert" className="error">{error}</p>}
        <RuleCompare state={state}/>
      </section></div>
  </main>;
}

function CustomerHome({state,run}:{state:AppState;run:(f:()=>AppState)=>void}) { return <><section className="serviceGrid">{services.map(s=><button className="serviceCard" key={s.id} onClick={()=>run(()=>createBooking(state,{customerId:state.session!.userId,service:s.id,locality:"Kharadi, Pune",scheduledAt:new Date().toISOString(),amount:760}))}><span className="serviceIcon">{s.icon}</span><strong>{s.name}</strong><span>{s.note}</span><small>Member nearby · {s.eta}</small></button>)}</section><section className="split"><article className="panel feature"><div><p className="eyebrow">Smart intake</p><h2>Show us the problem</h2><p>Add a reference photo and short description. AI can structure the request; it never chooses the worker or changes pay.</p></div><button className="secondary">Add photo / describe</button></article><article className="panel"><p className="eyebrow">Service location</p><h2>Kharadi, Pune</h2><div className="routeLine"><span>●</span><div></div><span>⌖</span></div><p className="muted">Live route and ETA appear after member acceptance.</p><button className="secondary">Change location</button></article></section></> }
function Orders({jobs}:{jobs:AppState["jobs"]}) { return <section className="panel"><div className="sectionTitle"><h2>Past & active orders</h2><span>{jobs.length} total</span></div>{jobs.length===0?<Empty text="No bookings yet. Your first service will appear here."/>:<div className="ticketList">{jobs.map(j=><article className="ticket" key={j.id}><div><small>{j.id} · {new Date(j.scheduledAt).toLocaleDateString()}</small><strong>{pretty(j.service)}</strong><span>{j.locality}</span></div><div className="ticketRight"><span className="statusChip">{labels[j.status]}</span><strong>₹{j.amount}</strong></div></article>)}</div>}</section> }
function Support({currentJob,onIssue}:{currentJob:AppState["jobs"][number]|undefined;onIssue:(c:string)=>void}) { return <section className="panel"><h2>Help without rating pressure</h2><p className="muted">Report a scope, safety, payment or service issue. Opening an issue does not automatically penalize a worker.</p><div className="actions">{["Scope / change","Safety","Payment","Service quality"].map(c=><button className="secondary" key={c} onClick={()=>onIssue(c)}>{c}</button>)}</div>{currentJob&&<p className="note">Linked to {currentJob.id}. Cooperative review creates a shared record.</p>}</section> }
function WorkerHome({state,job,receipt,run,worker}:{state:AppState;job:AppState["jobs"][number]|undefined;receipt:AppState["receipts"][number]|undefined;run:(f:()=>AppState)=>void;worker:AppState["workers"][number]|undefined}) { if(!job)return <Empty text="No task is assigned right now. Refusing work carries zero opportunity or rating penalty."/>; const next:Partial<Record<typeof job.status,typeof job.status>>={assigned:"accepted",accepted:"travelling",travelling:"arrived"}; return <><section className="jobHero"><div><p className="eyebrow">CURRENT JOB · {job.id}</p><h2>{pretty(job.service)} in {job.locality}</h2><div className="jobMeta"><span>⌖ 3.4 km</span><span>~18 min</span><span>Today, now</span></div></div><div className="payout"><small>PROTECTED PAYOUT</small><strong>₹{job.amount}</strong><span>No reverse bidding</span></div></section><section className="split"><article className="panel"><div className="sectionTitle"><h2>{labels[job.status]}</h2><span className="statusChip">{job.emergency?"Emergency":"Scheduled"}</span></div><div className="mapLite" aria-label="Route summary"><div className="road"></div><span className="pin workerPin">You</span><span className="pin customerPin">Job</span></div><p className="muted">Route: Kharadi cooperative zone · estimated arrival 18 min</p>{next[job.status]&&<button onClick={()=>run(()=>transitionJob(state,job.id,next[job.status]!))}>{next[job.status]==="accepted"?"Accept job":next[job.status]==="travelling"?"Start travel":"Mark arrived"}</button>}</article><article className="panel"><p className="eyebrow">WHY YOU GOT THIS JOB</p><h2>Fair Work receipt</h2><ul className="checkList"><li>✓ Skill certified for {pretty(job.service)}</li><li>✓ Inside service radius</li><li>✓ Workload under safety limit</li><li>✓ Lower safe workload won ordering</li></ul><p className="note">Receipt {receipt?.id || "pending"} · policy {state.policy.version}</p></article></section><section className="statRow"><div><small>Today</small><strong>{Math.round((worker?.workloadTodayMinutes||0)/60)}h {(worker?.workloadTodayMinutes||0)%60}m</strong><span>Workload safe</span></div><div><small>Rating</small><strong>{worker?.rating.toFixed(1)}</strong><span>Deactivation firewall on</span></div><div><small>Opportunity</small><strong>Normalized</strong><span>Refusal = no penalty</span></div></section></> }
function FairWork({state,receipt,worker}:{state:AppState;receipt:AppState["receipts"][number]|undefined;worker:AppState["workers"][number]|undefined}) { return <section className="panel"><p className="eyebrow">DECISION RECEIPT + REPLAY COURT</p><h2>Your allocation is explainable</h2><p className="muted">Hard eligibility is checked before livelihood ordering. The receipt freezes the rule and inputs used at dispatch.</p><div className="receiptGrid"><div><small>Policy</small><strong>{receipt?.policyVersion||state.policy.version}</strong></div><div><small>Protected payout</small><strong>₹{receipt?.protectedPayout||state.policy.minimumPayout}</strong></div><div><small>Safe workload</small><strong>{worker?.workloadTodayMinutes||0} / 480 min</strong></div><div><small>Challenge route</small><strong>Replay Court</strong></div></div><button className="secondary">Challenge this decision</button></section> }
function Earnings({jobs}:{jobs:AppState["jobs"]}) { const total=jobs.filter(j=>j.status==="settled").reduce((a,j)=>a+j.amount,0); return <section className="panel"><h2>Earnings ledger</h2><div className="bigNumber">₹{total.toLocaleString("en-IN")}</div><p className="muted">Settled earnings. Every payout preserves the cooperative floor and job-linked settlement record.</p><div className="ticketList">{jobs.map(j=><article className="ticket" key={j.id}><strong>{j.id}</strong><span>{pretty(j.service)}</span><span className="ticketRight">₹{j.amount} · {labels[j.status]}</span></article>)}</div></section> }
function Governance({state}:{state:AppState}) { return <section className="panel"><p className="eyebrow">ONE MEMBER · ONE VOTE</p><h2>Rules change through members, not admins</h2><div className="proposal"><div><strong>Constitution {state.policy.version}</strong><span>Current protected payout floor ₹{state.policy.minimumPayout}</span></div><span className="statusChip">Active</span></div><p className="note">Counterfactual simulation precedes voting. Quorum and approval are required before activation; old receipts remain frozen.</p></section> }
function AdminView({state,tab}:{state:AppState;tab:string}) { if(tab==="workers") return <section className="panel"><div className="sectionTitle"><h2>Worker registry</h2><span>{state.workers.filter(w=>w.verified).length} verified</span></div><div className="ticketList">{state.workers.map(w=><article className="ticket" key={w.id}><div><strong>{w.name}</strong><span>{w.skills.map(pretty).join(" · ")}</span></div><div className="ticketRight"><span>{w.cooperativeId}</span><strong>{w.rating} ★</strong></div></article>)}</div></section>;
 if(tab==="issues") return <section className="panel"><div className="sectionTitle"><h2>Issues & challenges</h2><span>{state.issues.length} records</span></div>{state.issues.length?state.issues.map(i=><div className="proposal" key={i.id}><div><strong>{i.category}</strong><span>{i.jobId||"General"} · opened by {i.openedBy}</span></div><span className="statusChip">{i.status}</span></div>):<Empty text="No open issues. Service and worker challenges will be linked here."/>}</section>;
 if(tab==="governance") return <><Governance state={state}/><section className="panel"><p className="eyebrow">COUNTERFACTUAL POLICY TWIN</p><h2>Same jobs. Same workers. Test a different rule.</h2><p className="muted">Compare distribution, wait time and worker-protection impact before a member ballot. Simulation cannot activate policy.</p><button>Run policy simulation</button></section></>;
 if(tab==="demand") return <section className="panel"><h2>Demand forecast & workforce allocation</h2><div className="forecast"><div style={{height:"46%"}}><span>Mon</span></div><div style={{height:"62%"}}><span>Tue</span></div><div style={{height:"78%"}}><span>Wed</span></div><div style={{height:"55%"}}><span>Thu</span></div><div style={{height:"88%"}}><span>Fri</span></div><div style={{height:"70%"}}><span>Sat</span></div><div style={{height:"50%"}}><span>Sun</span></div></div><p className="note">Synthetic SIH demo forecast. Used for staffing guidance, never automatic worker penalties.</p></section>;
 if(tab==="federation") return <section className="panel"><p className="eyebrow">FEDERATION MESH</p><h2>Cooperative first, worker second</h2><div className="federationFlow"><strong>Kharadi demand</strong><span>→</span><strong>Eligible cooperative</strong><span>→</span><strong>Its constitution</strong><span>→</span><strong>Worker member</strong></div><p className="note">Federation routing cannot undercut protected payout or worker safeguards.</p></section>;
 if(tab==="settlements") return <section className="panel"><h2>Settlements & invoices</h2><div className="ticketList">{state.jobs.map(j=><article className="ticket" key={j.id}><strong>{j.id}</strong><span>Customer invoice ₹{j.amount}</span><span className="ticketRight">{labels[j.status]}</span></article>)}</div></section>;
 return <><section className="metricGrid"><article><small>Open jobs</small><strong>{state.jobs.filter(j=>!["settled","cancelled"].includes(j.status)).length}</strong><span>Across member co-ops</span></article><article><small>Verified workers</small><strong>{state.workers.filter(w=>w.verified).length}</strong><span>Certification current</span></article><article><small>Protection floor</small><strong>₹{state.policy.minimumPayout}</strong><span>No reverse bidding</span></article><article><small>Open issues</small><strong>{state.issues.filter(i=>i.status==="open").length}</strong><span>Linked review records</span></article></section><section className="panel"><div className="sectionTitle"><h2>Live work register</h2><span>Shared state</span></div>{state.jobs.length? <div className="ticketList">{state.jobs.map(j=><article className="ticket" key={j.id}><div><small>{j.id}</small><strong>{pretty(j.service)} · {j.locality}</strong></div><div className="ticketRight"><span>{j.workerId||"Awaiting allocation"}</span><span className="statusChip">{labels[j.status]}</span></div></article>)}</div>:<Empty text="No live jobs yet. Create a booking from the customer view to populate operations."/>}</section></> }
function RuleCompare({state}:{state:AppState}) { return <section className="ruleCompare" aria-label="Cooperative rule comparison"><div><span>SAME JOBS</span><strong>{state.jobs.length}</strong></div><div><span>SAME WORKERS</span><strong>{state.workers.length}</strong></div><div className="different"><span>DIFFERENT RULES</span><strong>{state.policy.version}</strong></div></section> }
function Empty({text}:{text:string}) { return <div className="empty"><span>○</span><p>{text}</p></div> }
function pretty(s:string){return s.charAt(0).toUpperCase()+s.slice(1).replaceAll("_"," ")}
