"use client";

import { useState } from "react";
import type { AppState } from "@/lib/domain";
import { activatePolicyProposal, validatePolicyChange } from "@/lib/commands";

type Run=(fn:()=>AppState,message?:string)=>void;

export function AdminGovernance({state,run}:{state:AppState;run:Run}){
 const [guardResult,setGuardResult]=useState<string>("");
 const proposal=state.proposals.find(p=>p.id==="proposal-floor-860")??state.proposals[0];
 if(!proposal)return <section className="panel"><h2>No policy proposal</h2><p>Worker suggestions can be reviewed and developed into a simulated proposal.</p></section>;
 const votes=state.votes.filter(v=>v.proposalId===proposal.id),yes=votes.filter(v=>v.choice==="yes").length,no=votes.filter(v=>v.choice==="no").length;
 const validation=validatePolicyChange(state,{minimumPayout:proposal.proposedMinimumPayout,maxAddedWaitMinutes:proposal.proposedMaxAddedWaitMinutes});
 const quorum=votes.length>=9,approved=yes>=7;
 function testBannedRule(){const result=validatePolicyChange(state,{minimumPayout:state.policy.minimumPayout,maxAddedWaitMinutes:state.policy.maxAddedWaitMinutes,paidPriority:true});setGuardResult(result.valid?"Unexpectedly allowed":"Blocked: "+result.violations.join(" "));}
 return <div className="governancePage">
  <section className="governanceHero admin"><div><p className="eyebrow">COOPERATIVE DISPATCH CONSTITUTION</p><h2>Workers can change dispatch rules. They cannot vote away worker protections.</h2><p>Formal lifecycle: suggestion → protection validation → Policy Twin → personal impact review → one-member-one-vote → quorum → activation.</p></div><span className="statusChip">Active · {state.policy.version}</span></section>
  <section className="panel policyTwin"><div className="sectionTitle"><div><p className="eyebrow">COUNTERFACTUAL POLICY TWIN</p><h2>Same jobs. Same workers. Different rule.</h2></div><span className="statusChip">{proposal.status==="active"?"Activated":"Simulation frozen"}</span></div><div className="receiptGrid large"><div><small>Current floor</small><strong>₹{proposal.simulation.currentFloor}</strong><span>Active constitution</span></div><div><small>Proposed floor</small><strong>₹{proposal.simulation.proposedFloor}</strong><span>+₹{proposal.simulation.workerProtectionDelta}</span></div><div><small>Fair-wait allowance</small><strong>{proposal.simulation.currentMaxWait} → {proposal.simulation.proposedMaxWait} min</strong><span>Trade-off is explicit</span></div><div><small>Past records</small><strong>Frozen</strong><span>No retroactive rewrite</span></div></div><p className="muted">{proposal.simulation.note}</p></section>
  <section className="governanceTwoCol"><article className="panel protectionValidator"><div><p className="eyebrow">WORKER PROTECTION VALIDATOR</p><h2>Constitution boundaries</h2><p className="muted">A proposal must pass these checks before member votes can activate it.</p></div><ul className="checkList"><li><span>✓</span> Proposed payout ≥ current Worker Protection Floor</li><li><span>✓</span> Reverse auctions prohibited</li><li><span>✓</span> Paid ranking / boost fees prohibited</li><li><span>✓</span> Workload, Scope Lock, cancellation and rating safeguards remain outside ordinary policy votes</li></ul><div className={validation.valid?"validationResult pass":"validationResult fail"}><strong>{validation.valid?"Proposal passes protection validation":"Proposal blocked"}</strong>{!validation.valid&&validation.violations.map(v=><span key={v}>{v}</span>)}</div><button className="secondary" onClick={testBannedRule}>Test a paid-priority proposal</button>{guardResult&&<p className="guardResult" role="status">{guardResult}</p>}</article>
  <article className="panel ballotPanel"><div className="sectionTitle"><div><p className="eyebrow">MEMBER BALLOT</p><h2>{proposal.title}</h2></div><span className={`suggestionStatus ${proposal.status}`}>{proposal.status}</span></div><p>{proposal.description}</p><div className="ballotStats"><div><span>Participation</span><strong>{votes.length} / 9</strong><small>{quorum?"Quorum met":"Quorum pending"}</small></div><div><span>Support</span><strong>{yes} / 7</strong><small>{approved?"Approval threshold met":"Needs more support"}</small></div><div><span>Oppose</span><strong>{no}</strong><small>Dissent stays attached</small></div></div>{proposal.status==="active"?<div className="activationDone"><strong>{state.policy.version} is active</strong><span>Only later dispatches use it. Existing receipts remain unchanged.</span></div>:<button disabled={!quorum||!approved||!validation.valid} onClick={()=>run(()=>activatePolicyProposal(state,proposal.id),"Member-approved constitution activated. New dispatches use it; old receipts remain frozen.")}>{quorum&&approved?"Activate member-approved constitution":"Waiting for member quorum"}</button>}</article></section>
 </div>;
}
