"use client";

import { useState } from "react";
import type { AppState } from "@/lib/domain";
import { activatePolicyProposal, validatePolicyChange } from "@/lib/commands";
import { comparePolicyProposal } from "@/lib/policy-twin";
import { memberBallotOutcome } from "@/lib/ballot-outcome";
import { BALLOT_REQUIREMENTS, simulateBallot, type BallotSimulation } from "@/lib/governance-sim";
import { PolicyIntelligence } from "@/components/policy-intelligence";

type Run = (fn: () => AppState, message?: string) => boolean;
export function AdminGovernance({ state, run }: { state: AppState; run: Run }) {
  const [view, setView] = useState("rules"), [proposalId, setProposalId] = useState("");
  const [guardResult, setGuardResult] = useState("");
  const [simYes, setSimYes] = useState(7), [simNo, setSimNo] = useState(2);
  const [simResult, setSimResult] = useState<BallotSimulation | null>(null), [simError, setSimError] = useState("");
  const proposal = state.proposals.find(p => p.id === proposalId) ?? state.proposals.find(p => p.status === "voting") ?? state.proposals[0];
  const comparison = proposal ? comparePolicyProposal(state, proposal) : null;
  const result = proposal ? memberBallotOutcome(state, proposal, "") : null;
  const validation = proposal ? validatePolicyChange(state, { minimumPayout: proposal.proposedMinimumPayout, maxAddedWaitMinutes: proposal.proposedMaxAddedWaitMinutes }) : null;
  const votes = state.votes.filter(v => v.proposalId === proposal?.id);
  const historical = proposal?.status === "active" || proposal?.status === "rejected";
  const proposedTotal = comparison?.rows.reduce((sum, row) => sum + row.proposedPay, 0) ?? 0;
  const beforeTotal = comparison?.rows.reduce((sum, row) => sum + row.currentPay, 0) ?? 0;
  function testBannedRule() {
    const checked = validatePolicyChange(state, { minimumPayout: state.policy.minimumPayout, maxAddedWaitMinutes: state.policy.maxAddedWaitMinutes, paidPriority: true });
    setGuardResult(checked.valid ? "Unexpectedly allowed" : "Blocked: " + checked.violations.join(" "));
  }
  function runVoteSimulation() {
    setSimError("");
    try { setSimResult(simulateBallot({ yes: simYes, no: simNo, members: state.workers.length, quorumThreshold: BALLOT_REQUIREMENTS.participants, approvalThreshold: BALLOT_REQUIREMENTS.support })); }
    catch (error) { setSimResult(null); setSimError(error instanceof Error ? error.message : "Check the vote counts."); }
  }
  return <div className="adminStack">
    <section className="adminActiveRule"><div><span>Active constitution</span><strong>{state.policy.version}</strong></div><div><span>Minimum new-job pay</span><strong>₹{state.policy.minimumPayout}</strong></div><p>New dispatches use this rule. Existing decision receipts keep their original version.</p></section>
    <nav className="adminSubnav" aria-label="Governance workspace">{[["rules", "Rules & member votes"], ["voice", "Collective Pattern Court"], ["checks", "Protection checks & sandbox"]].map(([id, label]) => <button key={id} className={view === id ? "active" : ""} aria-current={view === id ? "page" : undefined} onClick={() => setView(id)}>{label}</button>)}</nav>
    {view === "voice" && <><div className="adminIntro"><h2>Listen before developing a rule</h2><p>Worker issues and ideas are evidence for discussion. AI drafts are advisory and cannot create a ballot, vote or activate policy.</p></div><PolicyIntelligence state={state} run={run}/></>}
    {view === "rules" && (proposal && comparison && result ? <>
      <section className="panel adminProposalPicker"><label className="field"><span>Choose a saved proposal</span><select aria-label="Choose a saved proposal" value={proposal.id} onChange={e => setProposalId(e.target.value)}>{state.proposals.map(p => <option key={p.id} value={p.id}>{p.title} / {p.status}</option>)}</select></label><span className="statusChip">{proposal.status === "voting" ? "Voting open" : proposal.status === "active" ? result.stage === "active" ? "In use" : "Earlier rule" : proposal.status === "rejected" ? "Rejected" : "Not open for voting"}</span></section>
      <div className="adminIntro"><h2>{proposal.title}</h2><p>{proposal.description}</p></div>
      <section className="panel adminTwin"><h2>Policy Twin: what changes for members?</h2><p className="adminBasis">{historical ? "Earlier rule baseline" : "Currently active rule"} versus this proposal, applied to the same frozen job inputs. This is a counterfactual payout comparison, not money already earned.</p><div className="adminPayCompare"><div><span>{historical ? "Before this proposal" : "Active rule"}</span><strong>₹{comparison.before.floor}</strong><small>Minimum job pay</small></div><div><span>{historical ? "Approved / proposed rule" : "Proposed rule"}</span><strong>₹{comparison.after.floor}</strong><small>Minimum job pay</small></div></div><p><strong>{comparison.rows.filter(row => row.currentPay !== row.proposedPay).length} of {comparison.rows.length} replayable jobs have different pay.</strong> Combined comparison: ₹{beforeTotal.toLocaleString("en-IN")} to ₹{proposedTotal.toLocaleString("en-IN")}.</p><p className="adminBasis">{comparison.excluded.length} jobs excluded because frozen member inputs are missing or inconsistent. Quotes already above both floors stay unchanged. This pay-floor change does not change member order.</p><details className="adminDisclosure"><summary>Inspect each job in the comparison</summary>{comparison.rows.length ? <div className="adminTwinRows"><div><strong>Job / member</strong><strong>Before</strong><strong>Proposed</strong></div>{comparison.rows.map(row => <div key={row.receiptId}><span>{row.jobId}<small>{state.workers.find(w => w.id === row.workerId)?.name ?? row.workerId}</small></span><span>₹{row.currentPay}</span><span>₹{row.proposedPay}</span></div>)}</div> : <p>No replayable job yet. Book a service first to create frozen inputs for this comparison.</p>}</details><p className="adminBasis">Waiting setting: {comparison.before.wait} to {comparison.after.wait} minutes. Stored only; it currently has no effect on worker selection or arrival estimates.</p></section>
      <section className="panel adminBallot"><div className="sectionTitle"><h2>Member vote result</h2><span className="statusChip">{validation?.valid ? "Protection checks pass" : "Protection checks block activation"}</span></div><dl className="adminTotals"><div><dt>Members who voted</dt><dd>{result.participants}<small> / {BALLOT_REQUIREMENTS.participants} needed</small></dd></div><div><dt>Yes</dt><dd>{result.yes}<small> / {BALLOT_REQUIREMENTS.support} needed</small></dd></div><div><dt>No</dt><dd>{result.no}</dd></div></dl><p>{result.stage === "ready" ? "Member quorum and approval are met. This rule can now be activated." : result.stage === "active" ? "This member-approved rule is now in use for new dispatches." : result.stage === "superseded" ? "This is an earlier approved rule. The active constitution above has replaced it." : result.stage === "waiting" ? `${result.participantsNeeded} more participants and ${result.supportNeeded} more Yes votes needed. Workers vote in Our votes after reviewing their own impact.` : result.stage === "blocked" ? validation?.violations.join(" ") : "This proposal is not open for activation."}</p><details className="adminDisclosure"><summary>See saved ballots and reasons</summary><ul className="adminSavedVotes">{votes.map(v => <li key={v.memberId}><strong>{state.workers.find(w => w.id === v.memberId)?.name ?? v.memberId}</strong><span>{v.choice === "yes" ? "Yes" : "No"}</span>{v.reason && <p>{v.reason}</p>}</li>)}</ul><p className="adminBasis">One member, one vote. Reviews and dissent remain attached. Demo registers may contain seeded votes; this list is the saved record.</p></details>{proposal.status === "voting" && <button disabled={result.stage !== "ready"} onClick={() => run(() => activatePolicyProposal(state, proposal.id), "Member-approved constitution activated. New dispatches use it; old receipts remain frozen.")}>Activate member-approved constitution</button>}{result.stage === "active" && <div className="adminFinding"><strong>{state.policy.version} is active at ₹{state.policy.minimumPayout}</strong><p>Book another service to prove its receipt uses the new rule. Keep the earlier receipt alongside it.</p></div>}</section>
    </> : <section className="panel"><h2>No saved proposals</h2><p>Member suggestions can be reviewed for future policy development. No ballot has been invented.</p></section>)}
    {view === "checks" && <>
      <section className="panel"><h2>Protections a vote cannot remove</h2><ul className="adminProtectionList"><li>No payout-floor cuts</li><li>No paid queue priority or reverse auctions</li><li>Work limits, Scope Lock, safe refusal and cancellation protection remain</li><li>Low ratings go to human review; they do not deactivate a member</li></ul><button className="secondary" onClick={testBannedRule}>Test a paid-priority proposal</button>{guardResult && <p className="adminFinding" role="status">{guardResult}</p>}</section>
      <section className="panel"><h2>Try vote counts without casting votes</h2><p className="adminBasis">Sandbox for {state.workers.length} registered members. Needs {BALLOT_REQUIREMENTS.participants} participants and {BALLOT_REQUIREMENTS.support} Yes votes. This never changes saved ballots or the active policy.</p><div className="adminToolbar"><label className="field"><span>Simulated Yes votes</span><input type="number" min={0} max={state.workers.length} value={simYes} onChange={e => setSimYes(Number(e.target.value))}/></label><label className="field"><span>Simulated No votes</span><input type="number" min={0} max={state.workers.length} value={simNo} onChange={e => setSimNo(Number(e.target.value))}/></label><button onClick={runVoteSimulation}>Run voting simulation</button></div>{simError && <p className="error" role="alert">{simError}</p>}{simResult && <div className="adminFinding" role="status"><strong>{simResult.activationEligible ? "Would meet the vote thresholds" : "Would not meet the vote thresholds"}</strong><p>{simResult.summary}</p></div>}</section>
    </>}
  </div>;
}
