"use client";

import type { AppState } from "@/lib/domain";
import { createFederationDemo, replayFederationDecision } from "@/lib/commands";
import { simulateFederationTwin } from "@/lib/federation";
import { FederationMap } from "@/components/service-map";

type Run=(fn:()=>AppState,message?:string)=>void;

function MetricSet({title,metrics,accent=false}:{title:string;metrics:ReturnType<typeof simulateFederationTwin>["localOnly"];accent?:boolean}){
 return <article className={accent?"fedTwinCard accent":"fedTwinCard"}><h3>{title}</h3><div className="fedTwinMetrics"><div><span>Jobs served</span><strong>{metrics.served}</strong></div><div><span>Unfilled</span><strong>{metrics.unfilled}</strong></div><div><span>Average ETA</span><strong>{metrics.averageEta} min</strong></div><div><span>p90 ETA</span><strong>{metrics.p90Eta} min</strong></div><div><span>Cross-coop</span><strong>{metrics.crossCooperative}</strong></div><div><span>Protection violations</span><strong>{metrics.protectionViolations}</strong></div></div></article>;
}

export function FederationExchange({state,run}:{state:AppState;run:Run}){
 const opportunity=state.federation.opportunities[0];
 if(!opportunity)return <section className="panel"><h2>Federation Opportunity Exchange</h2><p>No frozen federation proof exists yet.</p><button onClick={()=>run(()=>createFederationDemo(state),"Protected federation proof created.")}>Create protected overflow proof</button></section>;
 const home=state.cooperatives.find(c=>c.id===opportunity.homeCooperativeId);
 const receiving=state.cooperatives.find(c=>c.id===opportunity.selectedCooperativeId);
 const worker=state.workers.find(w=>w.id===opportunity.workerId);
 const snapshot=state.federation.snapshots.find(s=>s.opportunityId===opportunity.id);
 const replay=state.federation.replays.find(r=>r.opportunityId===opportunity.id);
 const settlement=state.federation.settlements.find(s=>s.opportunityId===opportunity.id);
 const twin=simulateFederationTwin();
 return <div className="federationExchangePage">
  <section className="federationIntro"><div><span className="fedIcon" aria-hidden="true">⌘</span></div><div><h2>Federation Opportunity Exchange</h2><p>When one cooperative has excess demand and another has safe capacity, the opportunity can move without merging workers into one central pool.</p></div><button className="secondary" onClick={()=>run(()=>createFederationDemo(state),"A new frozen federation proof was created from the deterministic capacity scenario.")}>Run another proof</button></section>
  <FederationMap state={state} opportunity={opportunity}/>
  <section className="fedDecisionFlow" aria-label="Two-level federation decision"><div><span>Home cooperative</span><strong>{home?.locality??opportunity.homeCooperativeId}</strong><small>No safe local capacity within {opportunity.slaMinutes} min</small></div><b aria-hidden="true">›</b><div><span>Federation chooses the cooperative</span><strong>{receiving?.locality??opportunity.selectedCooperativeId} selected</strong><small>Capacity, protection and SLA passed</small></div><b aria-hidden="true">›</b><div><span>Cooperative chooses the worker</span><strong>{worker?.name??opportunity.workerId}</strong><small>{receiving?.locality} · {state.policy.version}</small></div></section>
  <section className="panel fedRequest"><div className="sectionTitle roomy"><div><h2>Live overflow request</h2><p className="muted">{opportunity.id} · {opportunity.service} · customer promise {opportunity.slaMinutes} min</p></div><span className="statusChip">{opportunity.status.toUpperCase()}</span></div><div className="fedCandidateTable" role="table" aria-label="Federation cooperative candidates"><div className="fedTableHead" role="row"><span>Cooperative</span><span>Capacity</span><span>ETA</span><span>Protection</span><span>Result</span></div>{opportunity.candidates.map(candidate=>{const coop=state.cooperatives.find(c=>c.id===candidate.cooperativeId);return <div className={candidate.cooperativeId===opportunity.selectedCooperativeId?"fedTableRow selected":"fedTableRow"} role="row" key={candidate.cooperativeId}><strong>{coop?.name??candidate.cooperativeId}</strong><span>{candidate.availableWorkers} available</span><span>{candidate.eta} min</span><span>{candidate.protectionCompatible?"Compatible":"Blocked"}</span><span>{candidate.eligible?"Selected":candidate.exclusionReason}</span></div>})}</div></section>
  <section className="fedReceipts"><article className="fedReceiptCard"><small>Receipt 1 / federation</small><h2>Why did this job move to {receiving?.locality}?</h2><ul><li>✓ {opportunity.candidates.find(c=>c.cooperativeId===opportunity.selectedCooperativeId)?.availableWorkers} certified workers safely available</li><li>✓ {opportunity.candidates.find(c=>c.cooperativeId===opportunity.selectedCooperativeId)?.eta}-minute arrival is inside the promise</li><li>✓ Worker protections match the federation covenant</li>{opportunity.candidates.filter(c=>!c.eligible).map(c=><li key={c.cooperativeId}>{state.cooperatives.find(x=>x.id===c.cooperativeId)?.locality}: {c.exclusionReason}</li>)}</ul><strong>Result: {receiving?.name} selected.</strong>{snapshot&&<button className="secondary" onClick={()=>run(()=>replayFederationDecision(state,snapshot.id),"Frozen federation decision replayed.")}>Replay frozen federation receipt</button>}{replay&&<div className={replay.status==="confirmed"?"fedReplay confirmed":"fedReplay violation"}><strong>Federation decision {replay.status}</strong><span>{replay.summary}</span></div>}</article><article className="fedReceiptCard worker"><small>Receipt 2 / worker</small><h2>Why did {worker?.name} receive it?</h2><ul><li>✓ Right verified skill</li><li>✓ Available and workload safe</li><li>✓ Customer still receives service on time</li><li>↑ Lower safe workload inside the receiving cooperative</li></ul><strong>Result: the receiving cooperative selected its own member.</strong><p>Federation never compared worker wages across cooperatives.</p></article></section>
  {settlement&&<section className="fedSettlement"><span>Illustrative settlement / no clearing claim</span><strong>₹{settlement.customerTotal} customer total = ₹{settlement.workerAmount} worker + ₹{settlement.welfareAmount} welfare + ₹{settlement.fulfillingCooperativeAmount} fulfilling cooperative</strong><small>{settlement.reconciles?"Reconciles exactly. No home-cooperative or federation fee is invented.":"Settlement requires review."}</small></section>}
  <section className="fedTwin"><div><h2>Local only vs Federation Mesh</h2><p>Same 12 capacity scenarios. Same cooperatives. Same worker protections.</p></div><div className="fedTwinGrid"><MetricSet title="Local only" metrics={twin.localOnly}/><MetricSet title="Federation Mesh" metrics={twin.mesh} accent/></div></section>
 </div>;
}
