"use client";
import { useEffect, useState } from "react";
import type { AppState, Job } from "@/lib/domain";
import type { TestInvoice } from "@/lib/payments";
import { attachTestInvoice, recordTestCapture, invoiceScope } from "@/lib/payment-commands";
type Run=(fn:()=>AppState,message?:string)=>boolean;
type Invoice=Omit<TestInvoice,"token">;
async function action(body:Record<string,unknown>,operator?:string){const response=await fetch("/api/payments",{method:"POST",headers:{"content-type":"application/json",...(operator?{"x-payment-operator":operator}:{})},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw new Error(data.error||"Payment request failed");return data as {invoice:Invoice;accessToken?:string;keyId?:string};}
function errorText(error:unknown){return error instanceof Error?error.message:"Payment request failed";}
async function checkoutScript(){
  if((window as Window&{Razorpay?:unknown}).Razorpay)return;
  await new Promise<void>((resolve,reject)=>{const script=document.createElement("script");script.src="https://checkout.razorpay.com/v1/checkout.js";script.onload=()=>resolve();script.onerror=()=>{script.remove();reject(new Error("Razorpay checkout could not load. Check your connection."));};document.head.appendChild(script);});
}
export function RazorpayTestCheckout({state,job,run}:{state:AppState;job:Job;run:Run}){
  const[busy,setBusy]=useState(false),[error,setError]=useState("");const saved=job.gatewayInvoice;if(!saved)return null;
  async function reconcile(){setBusy(true);setError("");try{const data=await action({action:"read",...saved});if(data.invoice.status!=="captured")throw new Error(`Payment is ${data.invoice.status}. No captured payment or earnings posted yet.`);run(()=>recordTestCapture(state,job.id,data.invoice as TestInvoice),"Razorpay test capture reconciled. Test earnings recorded; bank transfer remains separate.");}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function pay(){setBusy(true);setError("");try{const data=await action({action:"order",...saved});if(data.invoice.status==="captured"){run(()=>recordTestCapture(state,job.id,data.invoice as TestInvoice));return;}await checkoutScript();type Checkout={open:()=>void;on:(event:string,fn:()=>void)=>void};const Razorpay=(window as unknown as Window&{Razorpay:new(options:Record<string,unknown>)=>Checkout}).Razorpay;
    const checkout=new Razorpay({key:data.keyId,order_id:data.invoice.orderId,amount:data.invoice.total,currency:"INR",name:"KaamSabha test",description:`${job.id} / test money only`,notes:{invoice_id:data.invoice.id},handler:async(result:{razorpay_payment_id:string;razorpay_signature:string})=>{setBusy(true);try{const confirmed=await action({action:"verify",...saved,paymentId:result.razorpay_payment_id,signature:result.razorpay_signature});run(()=>recordTestCapture(state,job.id,confirmed.invoice as TestInvoice),"Captured in Razorpay test mode. Test earnings recorded; worker bank settlement is separate.");}catch(e){setError(errorText(e));}finally{setBusy(false);}},modal:{ondismiss:()=>setBusy(false)}});
    checkout.on("payment.failed",()=>{setError("Razorpay did not complete this payment. Check the recorded status before retrying.");setBusy(false);});checkout.open();
  }catch(e){setError(errorText(e));setBusy(false);}}
  return <section className="testCheckout"><h3>Razorpay test checkout</h3><p>Approved server invoice: ₹{job.amount}. Test money only. No real customer charge or bank payout.</p><div className="actions"><button disabled={busy} onClick={()=>void pay()}>{busy?"Checking payment…":"Open Razorpay test checkout"}</button><button className="secondary" disabled={busy} onClick={()=>void reconcile()}>Check payment status</button></div>{error&&<p role="alert">{error}</p>}</section>;
}
function OperatorJob({state,job,run,operator}:{state:AppState;job:Job;run:Run;operator:string}){
  const[invoice,setInvoice]=useState<Invoice|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function execute(kind:string,providerId?:string){setBusy(true);setError("");try{const saved=job.gatewayInvoice,receipt=state.receipts.find(r=>r.id===job.receiptId);let data;
    if(kind==="approve")data=await action({action:kind,jobId:job.id,workerId:job.workerId,receiptId:job.receiptId,scope:invoiceScope(job),amount:job.amount,protectionFloor:receipt?.protectionFloor??job.amount},operator);
    else data=await action({action:kind,...saved,orderId:providerId,transferId:providerId},operator);
    setInvoice(data.invoice);if(kind==="approve")run(()=>attachTestInvoice(state,job.id,data.invoice as TestInvoice,data.accessToken!),"Server invoice approved and frozen. Customer can open Razorpay test checkout.");
    if(kind==="read"&&data.invoice.status==="captured")run(()=>recordTestCapture(state,job.id,data.invoice as TestInvoice),"Test capture imported once. Bank payout remains separate.");
  }catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <article className="testInvoice"><div><h3>{job.id}</h3><p>{state.workers.find(w=>w.id===job.workerId)?.name} / ₹{job.amount} / commission ₹0</p><p>{job.intakeNote||job.service}</p>{job.changeOrders.some(c=>c.approved===true)&&<ul>{job.changeOrders.filter(c=>c.approved===true).map(c=><li key={c.id}>{c.description}: ₹{c.amountDelta}</li>)}</ul>}</div>{!job.gatewayInvoice?<><p>Review completed work, approved extras and the frozen receipt before authorising this exact invoice. Demo logins do not authorise money.</p><button className="secondary" disabled={busy||!operator||job.handoverHistory?.some(h=>h.payReviewRequired&&!h.payReviewNote)} onClick={()=>void execute("approve")}>Approve server test invoice</button></>:<><button className="secondary" disabled={busy} onClick={()=>void execute("read")}>Read server payment record</button>{invoice&&<><p role="status"><b>{invoice.status}</b> / {invoice.orderId??"No order"} / {invoice.paymentId??"No capture"}</p>{invoice.status==="captured"&&<><p>Customer test capture ₹{invoice.total/100} = member ₹{invoice.worker/100} + commission ₹{invoice.commission/100}.</p><p><b>Route transfer: {invoice.transfer?.status??"Not sent"}</b>. A transfer is not proof of bank settlement.</p>{invoice.transfer&&<p>Provider settlement: {invoice.transfer.settlementStatus??"Unverified"}. Reversed: {invoice.transfer.amountReversed===undefined?"Unverified":`₹${invoice.transfer.amountReversed/100}`}. Recorded provider fee/tax: {invoice.transfer.providerFees===undefined?"Unverified":`₹${invoice.transfer.providerFees/100} / ${invoice.transfer.providerTax===undefined?"tax unverified":`₹${invoice.transfer.providerTax/100}`}`}.</p>}<button className="secondary" disabled={busy||!operator||!!invoice.transfer} onClick={()=>void execute("transfer")}>Send test Route transfer</button></>}{(invoice.status==="order-review"||invoice.status==="ordering"||invoice.transfer)&&<form className="trustForm" onSubmit={e=>{e.preventDefault();void execute(invoice.status==="order-review"||invoice.status==="ordering"?"reconcile-order":"reconcile-transfer",String(new FormData(e.currentTarget).get("providerId")));}}><label className="field"><span>Provider reference from the test dashboard</span><input name="providerId" placeholder={invoice.transfer?"trf_…":"order_…"} required/></label><button className="secondary" disabled={busy||!operator}>Reconcile provider record</button></form>}</>}</>}{error&&<p role="alert">{error}</p>}</article>;
}
export function PaymentOperator({state,run}:{state:AppState;run:Run}){const[configuration,setConfiguration]=useState<{ready:boolean;reason:string;webhookConfigured:boolean}|null>(null),[operator,setOperator]=useState("");useEffect(()=>{let active=true;void fetch("/api/payments").then(r=>r.json()).then(data=>{if(active)setConfiguration(data);}).catch(()=>{if(active)setConfiguration({ready:false,reason:"Payment server is unavailable. Check the local server.",webhookConfigured:false});});return()=>{active=false;};},[]);return <section className="paymentOperator"><h2>Razorpay test payments</h2><p>Separate from the local demo ledger. Server-approved invoices, verified captures and recorded Route transfers. No live money.</p>{configuration?.ready?<><label className="field"><span>Payment operator token</span><input type="password" value={operator} onChange={e=>setOperator(e.target.value)} autoComplete="off"/></label><p className="trustNote">Kept only on this screen, never in browser storage. {configuration.webhookConfigured?"Webhook verification configured.":"Webhook secret missing; browser signature plus provider capture checks remain available."}</p>{state.jobs.filter(j=>j.status==="completed"||j.gatewayInvoice).map(j=><OperatorJob key={j.id} state={state} job={j} run={run} operator={operator}/>)}{!state.jobs.some(j=>j.status==="completed"||j.gatewayInvoice)&&<p>Complete a booking first. Its exact invoice will appear here for approval.</p>}</>:<p role="status">{configuration?.reason??"Checking payment configuration…"}</p>}</section>;}
