"use client";
import { useEffect, useState } from "react";
import type { AppState, Evidence, Job, ProofMedia, ProofReview } from "@/lib/domain";
import { addWorkProof, approveEmergencyReplacement, interruptJobForEmergency, reportJobConcern, reviewInterruptedPay, saveProofReview } from "@/lib/commands";
import { mediaRepository, sha256 } from "@/lib/media-repository";
import { proofInput } from "@/lib/proof-input";
type Run=(fn:()=>AppState,message?:string)=>boolean;
type Props={state:AppState;job:Job;run:Run};
const text={en:{proof:"Add work proof",before:"Before work",after:"Work done",explain:"What did you observe or do?",parts:"Parts used and why (or write None)",checks:"How did you check the result?",file:"Photo or short video (optional, up to 2 MB)",save:"Save proof",help:"Safety & help",report:"Send to cooperative",emergency:"I need to stop this job",reason:"Reason",remaining:"What work is still needed?",stop:"Stop and request a replacement"},hi:{proof:"काम का प्रमाण जोड़ें",before:"काम से पहले",after:"काम पूरा किया",explain:"आपने क्या देखा या किया?",parts:"कौन से पुर्जे और क्यों (नहीं तो कोई नहीं लिखें)",checks:"नतीजा कैसे जाँचा?",file:"फोटो या छोटा वीडियो (वैकल्पिक, 2 MB तक)",save:"प्रमाण सहेजें",help:"सुरक्षा और मदद",report:"सहकारी संस्था को भेजें",emergency:"मुझे यह काम रोकना है",reason:"कारण",remaining:"कौन सा काम बाकी है?",stop:"काम रोकें और दूसरा सदस्य माँगें"},mr:{proof:"कामाचा पुरावा जोडा",before:"कामापूर्वी",after:"केलेले काम",explain:"तुम्ही काय पाहिले किंवा केले?",parts:"कोणते भाग वापरले आणि का (नसल्यास नाही लिहा)",checks:"कामाचा परिणाम कसा तपासला?",file:"फोटो किंवा छोटा व्हिडिओ (ऐच्छिक, 2 MB पर्यंत)",save:"पुरावा जतन करा",help:"सुरक्षा आणि मदत",report:"सहकारी संस्थेकडे पाठवा",emergency:"मला हे काम थांबवायचे आहे",reason:"कारण",remaining:"कोणते काम बाकी आहे?",stop:"काम थांबवा आणि दुसरा सदस्य मागा"}};
export function PriceBreakdown({amount}:{amount:number}){return <div className="trustPrice"><dl><div><dt>Agreed service / member pay</dt><dd>₹{amount.toLocaleString("en-IN")}</dd></div><div><dt>Platform commission</dt><dd>₹0</dd></div><div><dt>Unapproved extras</dt><dd>₹0</dd></div></dl><p>Parts, extra work or another person cost nothing unless you approve a named addition first. No automatic helper charge. Demo quote; taxes and payment-provider charges are not integrated.</p></div>;}
export function ProofEditor({state,job,run}:Props){
  const t=text[state.locale],phase=job.status==="arrived"?"before":"after";
  const [busy,setBusy]=useState(false),[error,setError]=useState("");
  async function submit(form:HTMLFormElement){const data=new FormData(form),file=data.get("proofFile");let media:ProofMedia|undefined;setBusy(true);setError("");try{if(file instanceof File&&file.size)media=await mediaRepository.put(file);const success=run(()=>addWorkProof(state,job.id,{phase,explanation:String(data.get("explanation")??""),partsUsed:String(data.get("parts")??""),checksDone:String(data.get("checks")??""),media}),"Work proof saved on this device. The customer can inspect it.");if(!success&&media)await mediaRepository.remove(media.assetId);if(success)form.reset();}catch(e){setError(e instanceof Error?e.message:"Proof could not be saved");}finally{setBusy(false);}}
  return <form className="trustForm" onSubmit={e=>{e.preventDefault();void submit(e.currentTarget);}}><h3>{phase==="before"?t.before:t.proof}</h3><label className="field"><span>{t.explain}</span><textarea name="explanation" required maxLength={2000}/></label>{phase==="after"&&<><label className="field"><span>{t.parts}</span><input name="parts" required maxLength={1000}/></label><label className="field"><span>{t.checks}</span><textarea name="checks" required maxLength={1000}/></label></>}<label className="field"><span>{t.file}</span><input type="file" name="proofFile" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm"/></label><p className="trustNote">Stored on this device, including after refresh. Upload only with the customer’s consent. Text-only proof is a member statement, not verified media.</p>{error&&<p role="alert">{error}</p>}<button disabled={busy}>{busy?"Saving…":t.save}</button></form>;
}
function ProofAsset({proof}:{proof:Evidence}){const[url,setUrl]=useState(""),[missing,setMissing]=useState(false),[playError,setPlayError]=useState(false);useEffect(()=>{let active=true,objectUrl="";if(!proof.media)return;void mediaRepository.get(proof.media.assetId).then(blob=>{if(!active)return;if(blob){objectUrl=URL.createObjectURL(blob);setUrl(objectUrl);}else setMissing(true);}).catch(()=>{if(active)setMissing(true);});return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[proof.media]);return <article className="proofRecord"><header><strong>{proof.label}</strong><small>Member {proof.uploadedBy} / {new Date(proof.createdAt).toLocaleString()}</small></header><p>{proof.explanation??"Legacy demo label; no photo or video is attached."}</p>{proof.partsUsed&&<p><b>Parts and reason: </b>{proof.partsUsed}</p>}{proof.checksDone&&<p><b>Result check: </b>{proof.checksDone}</p>}{url&&(proof.media?.mimeType.startsWith("video/")?<video src={url} onError={()=>setPlayError(true)} controls preload="auto" aria-label={proof.media.name}/>:<img src={url} onError={()=>setPlayError(true)} alt={proof.explanation||"Work proof"}/>)}{playError&&<p role="status">This file cannot be shown here. Ask the member for a supported photo or video.</p>}{missing&&<p role="status">This file is missing from this device. Ask the member to attach it again.</p>}{proof.media?<details><summary>File record</summary><small>{proof.media.name} / {Math.ceil(proof.media.size/1024)} KB<br/>SHA-256: {proof.media.digest}</small></details>:<small>Member statement only. No media verification.</small>}</article>;}
function dataUrl(blob:Blob):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error("Could not read the saved proof"));reader.readAsDataURL(blob);});}
export function ProofRecords({state,job,run}:Props){const[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[stale,setStale]=useState(false);
  useEffect(()=>{let active=true;if(job.proofReview)void sha256(JSON.stringify(proofInput(job))).then(d=>{if(active)setStale(d!==job.proofReview?.inputDigest);}).catch(()=>{if(active)setStale(true);});return()=>{active=false;};},[job]);
  async function review(){setBusy(true);setError("");try{const media=[];for(const proof of job.evidence){if(!proof.media)continue;const blob=await mediaRepository.get(proof.media.assetId);if(!blob)throw new Error("A saved proof file is missing. Attach it again before AI review.");media.push({data:await dataUrl(blob)});}if(media.length>4||JSON.stringify(media).length>3.8*1024*1024)throw new Error("This proof record is too large for one AI request. The customer and cooperative can inspect the saved files; AI has not reviewed them.");const response=await fetch("/api/ai/proof",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({input:proofInput(job),media,consent})}),report=await response.json();if(!response.ok)throw new Error(report.error||"Proof review is unavailable");run(()=>saveProofReview(state,job.id,report as ProofReview),report.mode==="ai-assisted"?"Advisory review saved. A human still decides.":"AI unavailable. Your proof is saved for human review.");}catch(e){setError(e instanceof Error?e.message:"Review failed");}finally{setBusy(false);}}
  if(!job.evidence.length)return null;
  return <details className="trustDisclosure"><summary>Inspect work proof ({job.evidence.length})</summary><div className="trustBody">{job.evidence.map(p=><ProofAsset key={p.id} proof={p}/>)}<section className="proofAdvice"><h3>Ask AI to check the evidence</h3><p>It can ask about missing proof or an unexplained part. It cannot certify a hidden repair, decide blame or change anyone’s pay.</p><label className="checkField"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I agree to send this scope and proof to the configured AI provider.</span></label><button className="secondary" disabled={!consent||busy||!job.evidence.some(e=>e.media)} onClick={()=>void review()}>{busy?"Reviewing evidence…":"Request advisory review"}</button>{error&&<p role="alert">{error}</p>}{job.proofReview&&<div className="proofVerdict" role="status"><strong>{stale?"Earlier review: check current evidence":job.proofReview.mode==="ai-assisted"?"AI notes for human review":"Not reviewed by AI"}</strong><p>{job.proofReview.summary}</p>{job.proofReview.observations.map((s,i)=><p key={`o${i}`}>{s}</p>)}{job.proofReview.questions.length>0&&<><b>Questions to discuss</b><ul>{job.proofReview.questions.map((s,i)=><li key={i}>{s}</li>)}</ul></>}{job.proofReview.limitations.map((s,i)=><small key={`l${i}`}>{s}</small>)}</div>}</section></div></details>;
}
export function SafetyHelp({state,job,run}:Props){const t=text[state.locale],[category,setCategory]=useState("Safety concern");return <><div className="trustSafetyActions"><a className="emergencyCall" href="tel:112">SOS: Call 112</a><small>Immediate danger only. Opens your phone dialer.</small></div><details className="trustDisclosure"><summary>{t.help}</summary><div className="trustBody"><p className="trustNote">This opens your phone dialer. KaamSabha does not automatically contact police, send your location or notify an external safety team.</p><form className="trustForm" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;if(run(()=>reportJobConcern(state,job.id,category,String(new FormData(form).get("details"))),"Concern saved with this job and decision receipt for cooperative review."))form.reset();}}><label className="field"><span>What is wrong?</span><select aria-label="What is wrong?" value={category} onChange={e=>setCategory(e.target.value)}>{["Safety concern","Unapproved helper","Unlisted charge","Work quality or damage","Payment concern"].map(c=><option key={c}>{c}</option>)}</select></label><label className="field"><span>Tell us what happened</span><textarea name="details" required minLength={5} maxLength={2000}/></label><button className="secondary">{t.report}</button></form><p className="trustNote">Saved in this shared demo register. The cooperative replies in Help requests. No automatic ban, rating cut or pay deduction.</p>{state.issues.filter(i=>i.jobId===job.id&&i.openedBy===state.session?.userId).map(i=><div className="trustCase" key={i.id}><strong>{i.category}: {i.status}</strong><small>{i.id}</small>{i.notes.map((n,k)=><p key={k}>{n}</p>)}</div>)}</div></details></>;}
export function EmergencyStop({state,job,run}:Props){const t=text[state.locale];if(!["accepted","travelling","arrived","started","change_pending"].includes(job.status))return null;return <details className="trustDisclosure emergencyDisclosure"><summary>{t.emergency}</summary><form className="trustForm" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);run(()=>interruptJobForEmergency(state,job.id,String(d.get("reason")),String(d.get("remaining"))),"Job paused. The customer must approve a replacement. Your availability is paused; no rating or opportunity penalty.");}}><p>If you need to leave, stop safely. Your current offer ends and your availability pauses. The customer agrees to a replacement; your earlier receipt and proof stay saved.</p><label className="field"><span>{t.reason}</span><select name="reason" aria-label={t.reason}><option>Family emergency</option><option>Accident or health emergency</option><option>Unsafe environment</option><option>Unable to continue safely</option></select></label><label className="field"><span>{t.remaining}</span><textarea name="remaining" required maxLength={1200}/></label><button className="dangerGhost">{t.stop}</button><small>Started work goes to the cooperative for a separate pay review; it is not automatically erased or deducted.</small></form></details>;}
export function HandoverRecord({state,job,run}:Props){
  const latest=job.handoverHistory?.at(-1);if(!latest)return null;
  const customer=state.session?.role==="customer",admin=state.session?.role==="admin";
  const history=job.handoverHistory?.map(h=><div key={h.id}><p><b>{state.workers.find(w=>w.id===h.fromWorkerId)?.name}: </b>{h.reason}</p><p>Still needed: {h.remainingWork}</p><small>Original decision {h.fromReceiptId}. {h.newReceiptId&&`Replacement decision ${h.newReceiptId}.`} No opportunity or rating penalty.</small>{h.payReviewRequired&&<p><b>Interrupted member’s pay review: </b>{h.payReviewNote??"Pending cooperative review; no payment has been promised or deducted."}</p>}{admin&&h.payReviewRequired&&!h.payReviewNote&&<form className="trustForm" onSubmit={e=>{e.preventDefault();run(()=>reviewInterruptedPay(state,job.id,h.id,String(new FormData(e.currentTarget).get("review"))),"Interrupted-work pay review recorded. This note does not transfer funds.");}}><label className="field"><span>Pay review, funding and next action</span><textarea name="review" required minLength={10} maxLength={2000}/></label><button className="secondary">Record human pay review</button></form>}</div>);
  return <section className="handoverRecord">
    <h3>{latest.status==="reassigned"?"Replacement agreed":"This job needs a replacement"}</h3>
    {customer&&job.status==="completed"&&job.handoverHistory?.some(h=>h.payReviewRequired&&!h.payReviewNote)&&<p className="trustNote"><b>Pending cooperative review.</b> Payment opens after the cooperative records its review of interrupted work. No amount has been promised or deducted.</p>}
    {customer&&latest.status!=="reassigned"&&<>
      <p>{state.workers.find(w=>w.id===latest.fromWorkerId)?.name??"Your worker"} had to stop. Still needed: {latest.remainingWork}</p>
      <div className="customerReplacementQuote"><span>Total for the remaining service</span><strong>₹{Math.max(job.amount,state.policy.minimumPayout)}</strong></div>
      <p className="trustNote">Approve this amount to find one replacement. The new worker needs fresh start and finish codes.</p>
      <button onClick={()=>run(()=>approveEmergencyReplacement(state,job.id),"Replacement checked under the active constitution. See the new member and receipt, or the capacity waiting state.")}>{latest.status==="awaiting-capacity"?"Check replacement capacity again":"Agree and find a replacement"}</button>
    </>}
    {customer?<details className="trustDisclosure"><summary>Replacement history and pay review</summary>{history}</details>:history}
  </section>;
}
