import type { AppState, DecisionReceipt, Job, OtpChallenge, Role, SuggestionCategory } from "./domain.ts";
import { selectCooperative, selectWorkerInCooperative, workerDailyLimit } from "./domain.ts";

function nextRevision(state:AppState):AppState{return{...state,revision:state.revision+1};}
function id(prefix:string,revision:number){return`${prefix}-${String(revision+1).padStart(5,"0")}`;}
function requireRole(state:AppState,role:Role){if(state.session?.role!==role)throw new Error(`${role} session required`);}
function jobById(state:AppState,jobId:string){const job=state.jobs.find(j=>j.id===jobId);if(!job)throw new Error("Job not found");return job;}
function replaceJob(state:AppState,nextJob:Job){return state.jobs.map(j=>j.id===nextJob.id?nextJob:j);}
function currentWorker(state:AppState){requireRole(state,"worker");const worker=state.workers.find(w=>w.id===state.session!.userId);if(!worker)throw new Error("Verified worker-member required");return worker;}
function receiptFor(state:AppState,jobId:string,service:string,amount:number,cooperativeId:string,workerId:string,receiptId:string):DecisionReceipt{const worker=state.workers.find(w=>w.id===workerId)!;const cooperative=state.cooperatives.find(c=>c.id===cooperativeId)!;return{id:receiptId,jobId,policyVersion:cooperative.policyVersion,workerId,cooperativeId,hardChecks:{verified:worker.verified,active:worker.active,available:worker.available,skill:worker.skills.includes(service),workloadSafe:worker.workloadTodayMinutes<workerDailyLimit(worker)},protectedPayout:Math.max(amount,state.policy.minimumPayout),estimatedCost:87,estimatedNet:Math.max(amount,state.policy.minimumPayout)-87,federationReason:"Federation selected an eligible cooperative by protected capacity; the federation never selects the cheapest worker.",reason:"Inside the receiving cooperative, hard eligibility and workload safety passed before opportunity ordering; stable worker ID is the final tie-break.",createdAt:new Date().toISOString()};}

export function signIn(state:AppState,userId:string,role:Role):AppState{const clean=userId.trim();if(!clean)throw new Error("User ID is required");if(role==="worker"){const worker=state.workers.find(w=>w.id===clean||w.name.toLowerCase().includes(clean.toLowerCase()));if(!worker)throw new Error("Worker account is not linked to a verified member");return nextRevision({...state,session:{userId:worker.id,role}});}return nextRevision({...state,session:{userId:clean,role}});}
export function signOut(state:AppState):AppState{return nextRevision({...state,session:null});}

export function createBooking(state:AppState,input:{customerId:string;service:string;locality:string;scheduledAt:string;emergency?:boolean;amount?:number;intakeNote?:string;referenceName?:string}):AppState{requireRole(state,"customer");if(!input.locality.trim()||!input.service.trim())throw new Error("Service and location are required");const cooperative=selectCooperative(state,input.service);const worker=cooperative?selectWorkerInCooperative(state,cooperative.id,input.service):undefined;const jobId=id("KMS",state.revision),receiptId=`${jobId}-receipt`,amount=Math.max(input.amount??state.policy.minimumPayout,state.policy.minimumPayout);const job:Job={id:jobId,customerId:input.customerId,service:input.service,locality:input.locality,scheduledAt:input.scheduledAt,emergency:Boolean(input.emergency),status:worker?"assigned":"requested",workerId:worker?.id,cooperativeId:cooperative?.id,receiptId:worker?receiptId:undefined,amount,intakeNote:input.intakeNote?.trim()||"",referenceName:input.referenceName?.trim()||"",declinedWorkerIds:[],evidence:[],changeOrders:[]};const receipt=worker&&cooperative?receiptFor(state,jobId,input.service,amount,cooperative.id,worker.id,receiptId):undefined;return nextRevision({...state,jobs:[job,...state.jobs],receipts:receipt?[receipt,...state.receipts]:state.receipts});}

export function transitionJob(state:AppState,jobId:string,next:Job["status"]):AppState{const allowed:Record<Job["status"],Job["status"][]>={requested:["assigned","cancelled"],assigned:["accepted","cancelled"],accepted:["travelling","cancelled"],travelling:["arrived"],arrived:[],started:["change_pending"],change_pending:["started"],completed:["settled"],settled:[],cancelled:[]};const job=jobById(state,jobId);if(!allowed[job.status].includes(next))throw new Error(`Invalid transition ${job.status} → ${next}`);return nextRevision({...state,jobs:replaceJob(state,{...job,status:next})});}

export function declineJobSafely(state:AppState,jobId:string,reason:string):AppState{const worker=currentWorker(state),job=jobById(state,jobId);if(job.workerId!==worker.id||job.status!=="assigned")throw new Error("Only the assigned worker can safely decline an unaccepted offer");const cleanReason=reason.trim();if(!cleanReason)throw new Error("Choose or describe a safe-decline reason");const excluded=[...(job.declinedWorkerIds||[]),worker.id];const cooperative=selectCooperative(state,job.service,excluded);const nextWorker=cooperative?selectWorkerInCooperative(state,cooperative.id,job.service,excluded):undefined;const receiptId=nextWorker&&cooperative?id("DEC",state.revision):undefined;const nextJob:Job={...job,status:nextWorker?"assigned":"requested",workerId:nextWorker?.id,cooperativeId:cooperative?.id,receiptId,declinedWorkerIds:excluded};const receipt=nextWorker&&cooperative&&receiptId?receiptFor(state,job.id,job.service,job.amount,cooperative.id,nextWorker.id,receiptId):undefined;const record={id:id("REF",state.revision),jobId:job.id,workerId:worker.id,reason:cleanReason,penalty:0 as const,createdAt:new Date().toISOString()};return nextRevision({...state,jobs:replaceJob(state,nextJob),receipts:receipt?[receipt,...state.receipts]:state.receipts,safeDeclines:[record,...state.safeDeclines]});}

export function cancelBookingProtected(state:AppState,jobId:string,reason:string):AppState{requireRole(state,"customer");const job=jobById(state,jobId);if(job.customerId!==state.session!.userId)throw new Error("Booking customer required");if(!["requested","assigned","accepted","travelling"].includes(job.status))throw new Error("Cancellation is unavailable after arrival; use support or Scope Lock instead");if(state.cancellations.some(c=>c.jobId===jobId))throw new Error("Cancellation already recorded");const workerPayout=["accepted","travelling"].includes(job.status)?Math.round(state.policy.minimumPayout*0.25):0;const customerRefund=Math.max(0,job.amount-workerPayout);const record={id:id("CAN",state.revision),jobId,cancelledBy:state.session!.userId,reason:reason.trim()||"Customer cancellation",workerPayout,customerRefund,createdAt:new Date().toISOString()};return nextRevision({...state,jobs:replaceJob(state,{...job,status:"cancelled"}),cancellations:[record,...state.cancellations]});}

export function recordOtpIssued(state:AppState,jobId:string,challenge:OtpChallenge):AppState{const job=jobById(state,jobId);if(challenge.purpose==="start"){if(state.session?.role!=="customer"||state.session.userId!==job.customerId)throw new Error("Customer who booked the job must issue start OTP");if(job.status!=="arrived")throw new Error("Start OTP is available only after worker arrival");return nextRevision({...state,jobs:replaceJob(state,{...job,startOtp:challenge})});}if(state.session?.role!=="customer"||state.session.userId!==job.customerId)throw new Error("Customer who booked the job must issue completion OTP");if(!["started","change_pending"].includes(job.status))throw new Error("Completion OTP is available only while work is active");if(!job.evidence.length)throw new Error("Review at least one work proof before issuing completion OTP");if(job.changeOrders.some(c=>c.approved===undefined))throw new Error("Resolve pending change orders first");return nextRevision({...state,jobs:replaceJob(state,{...job,completionOtp:challenge})});}
export function recordOtpFailure(state:AppState,jobId:string,purpose:"start"|"completion"):AppState{const job=jobById(state,jobId),field=purpose==="start"?"startOtp":"completionOtp",challenge=job[field];if(!challenge)throw new Error("OTP was not issued");return nextRevision({...state,jobs:replaceJob(state,{...job,[field]:{...challenge,attemptsLeft:Math.max(0,challenge.attemptsLeft-1)}})});}
export function recordOtpVerified(state:AppState,jobId:string,purpose:"start"|"completion"):AppState{const worker=currentWorker(state),job=jobById(state,jobId);if(job.workerId!==worker.id)throw new Error("Only the assigned worker can verify this OTP");const field=purpose==="start"?"startOtp":"completionOtp",challenge=job[field];if(!challenge)throw new Error("OTP was not issued");if(challenge.usedAt)throw new Error("OTP already used");if(challenge.expiresAt<Date.now())throw new Error("OTP expired");if(challenge.attemptsLeft<=0)throw new Error("OTP locked");if(purpose==="start"&&job.status!=="arrived")throw new Error("Worker must be marked arrived before start OTP");if(purpose==="completion"&&!["started","change_pending"].includes(job.status))throw new Error("Job must be in progress before completion OTP");return nextRevision({...state,jobs:replaceJob(state,{...job,[field]:{...challenge,usedAt:Date.now()},status:purpose==="start"?"started":"completed"})});}

export function addEvidence(state:AppState,jobId:string,label:string):AppState{const worker=currentWorker(state),job=jobById(state,jobId);if(job.workerId!==worker.id)throw new Error("Assigned worker required");if(!["started","change_pending"].includes(job.status))throw new Error("Work must be started before adding evidence");const evidence={id:id("EV",state.revision),label:label.trim()||"Before/after work proof",createdAt:new Date().toISOString(),uploadedBy:worker.id};return nextRevision({...state,jobs:replaceJob(state,{...job,evidence:[...job.evidence,evidence]})});}
export function requestChangeOrder(state:AppState,jobId:string,description:string,amountDelta:number):AppState{const worker=currentWorker(state),job=jobById(state,jobId);if(job.workerId!==worker.id||job.status!=="started")throw new Error("Change order requires an active assigned job");if(!description.trim()||amountDelta<0)throw new Error("Describe the scope change and use a non-negative amount");const change={id:id("CHG",state.revision),description:description.trim(),amountDelta,requestedBy:worker.id};return nextRevision({...state,jobs:replaceJob(state,{...job,status:"change_pending",changeOrders:[...job.changeOrders,change]})});}
export function decideChangeOrder(state:AppState,jobId:string,changeId:string,approved:boolean):AppState{requireRole(state,"customer");const job=jobById(state,jobId);if(job.customerId!==state.session!.userId||job.status!=="change_pending")throw new Error("Booking customer approval required");const target=job.changeOrders.find(c=>c.id===changeId&&c.approved===undefined);if(!target)throw new Error("Pending change order not found");const changeOrders=job.changeOrders.map(c=>c.id===changeId?{...c,approved,decidedAt:new Date().toISOString()}:c),amount=approved?Math.max(state.policy.minimumPayout,job.amount+target.amountDelta):job.amount;return nextRevision({...state,jobs:replaceJob(state,{...job,status:"started",changeOrders,amount})});}
export function settleJob(state:AppState,jobId:string):AppState{requireRole(state,"customer");const job=jobById(state,jobId);if(job.customerId!==state.session!.userId||job.status!=="completed")throw new Error("Completed booking customer required");if(state.settlements.some(s=>s.jobId===jobId))throw new Error("Job already settled");const workerPayout=Math.max(state.policy.minimumPayout,job.amount),settlement={id:id("SET",state.revision),jobId,amount:job.amount,workerPayout,platformFee:0,invoiceNumber:`INV-${job.id}`,settledAt:new Date().toISOString()};return nextRevision({...state,jobs:replaceJob(state,{...job,status:"settled"}),settlements:[settlement,...state.settlements]});}
export function addFeedback(state:AppState,jobId:string,rating:number,note:string):AppState{requireRole(state,"customer");const job=jobById(state,jobId);if(job.customerId!==state.session!.userId||job.status!=="settled")throw new Error("Feedback is available after settlement");if(rating<1||rating>5)throw new Error("Rating must be 1–5");if(state.feedback.some(f=>f.jobId===jobId&&f.customerId===state.session!.userId))throw new Error("Feedback already submitted");return nextRevision({...state,feedback:[{id:id("FB",state.revision),jobId,customerId:state.session!.userId,rating,note:note.trim(),createdAt:new Date().toISOString()},...state.feedback]});}

export function openIssue(state:AppState,openedBy:string,category:string,jobId?:string):AppState{if(!state.session)throw new Error("Signed-in session required");const clean=category.trim();if(!clean)throw new Error("Issue category is required");return nextRevision({...state,issues:[{id:id("ISS",state.revision),jobId,openedBy,category:clean,status:"open",notes:[]},...state.issues]});}
export function addIssueNote(state:AppState,issueId:string,note:string):AppState{if(!state.session)throw new Error("Signed-in session required");const clean=note.trim();if(!clean)throw new Error("Write a short note first");const issue=state.issues.find(i=>i.id===issueId);if(!issue)throw new Error("Issue not found");const prefix=state.session.role==="admin"?"Cooperative":state.session.role==="worker"?`Worker ${state.session.userId}`:`Customer ${state.session.userId}`;return nextRevision({...state,issues:state.issues.map(i=>i.id===issueId?{...i,status:"responded",notes:[...i.notes,`${prefix}: ${clean}`]}:i)});}
export function reviewIssue(state:AppState,issueId:string,status:"responded"|"closed"):AppState{requireRole(state,"admin");if(!state.issues.some(i=>i.id===issueId))throw new Error("Issue not found");return nextRevision({...state,issues:state.issues.map(i=>i.id===issueId?{...i,status}:i)});}

export function openChallenge(state:AppState,jobId:string,reason:string):AppState{const worker=currentWorker(state),job=jobById(state,jobId);if(job.workerId!==worker.id&&!state.receipts.some(r=>r.jobId===jobId&&r.workerId===worker.id))throw new Error("This worker has no receipt for that job");const receipt=state.receipts.find(r=>r.jobId===jobId&&r.workerId===worker.id)||state.receipts.find(r=>r.jobId===jobId);if(!receipt)throw new Error("Decision receipt not found");return nextRevision({...state,challenges:[{id:id("RPL",state.revision),jobId,workerId:worker.id,reason:reason.trim()||"Allocation review",status:"open",replaySummary:`Frozen replay uses ${receipt.policyVersion}; original worker ${receipt.workerId}; protected payout ₹${receipt.protectedPayout}.`,createdAt:new Date().toISOString()},...state.challenges]});}

export function submitPolicySuggestion(state:AppState,input:{category:SuggestionCategory;title:string;details:string}):AppState{const worker=currentWorker(state);const title=input.title.trim(),details=input.details.trim();if(title.length<4||details.length<10)throw new Error("Add a short title and explain the suggestion in a little more detail");const suggestion={id:id("SUG",state.revision),workerId:worker.id,category:input.category,title,details,status:"submitted" as const,createdAt:new Date().toISOString()};return nextRevision({...state,suggestions:[suggestion,...state.suggestions]});}
export function reviewPolicySuggestion(state:AppState,suggestionId:string,status:"under-review"|"accepted"|"declined"):AppState{requireRole(state,"admin");if(!state.suggestions.some(s=>s.id===suggestionId))throw new Error("Suggestion not found");return nextRevision({...state,suggestions:state.suggestions.map(s=>s.id===suggestionId?{...s,status,reviewedAt:new Date().toISOString()}:s)});}

export function updateWorkability(state:AppState,input:{available:boolean;maxDailyMinutes:number;minRestMinutes:number}):AppState{const worker=currentWorker(state);const maxDailyMinutes=Math.max(240,Math.min(600,Math.round(input.maxDailyMinutes))),minRestMinutes=Math.max(15,Math.min(120,Math.round(input.minRestMinutes)));return nextRevision({...state,workers:state.workers.map(w=>w.id===worker.id?{...w,available:input.available,maxDailyMinutes,minRestMinutes}:w)});}

export function reviewPolicyImpact(state:AppState,proposalId:string,memberId:string):AppState{const worker=currentWorker(state);if(worker.id!==memberId)throw new Error("Workers can review only their own impact");if(state.policyReviews.some(r=>r.proposalId===proposalId&&r.memberId===memberId))return state;return nextRevision({...state,policyReviews:[...state.policyReviews,{proposalId,memberId,reviewedAt:new Date().toISOString()}]});}
export function castVote(state:AppState,proposalId:string,memberId:string,choice:"yes"|"no"):AppState{const worker=currentWorker(state);if(worker.id!==memberId)throw new Error("One member can vote only for themselves");if(!state.policyReviews.some(r=>r.proposalId===proposalId&&r.memberId===memberId))throw new Error("Review your personal policy impact before voting");if(state.votes.some(v=>v.proposalId===proposalId&&v.memberId===memberId))throw new Error("One member can vote only once on a proposal");return nextRevision({...state,votes:[...state.votes,{proposalId,memberId,choice}]});}

export function simulatePolicy(state:AppState,minimumPayout:number){const floor=Math.max(state.policy.minimumPayout,minimumPayout);return{policyVersion:`sim-${state.revision+1}`,currentFloor:state.policy.minimumPayout,simulatedFloor:floor,affectedJobs:state.jobs.filter(j=>j.amount<floor).length,workerProtectionDelta:floor-state.policy.minimumPayout,note:"Counterfactual only. No dispatch, receipt, settlement or active policy is mutated."};}
