import type { Locale } from "./domain.ts";

// Whole phrases in each language; stored categories and decision facts stay unchanged.
const phrases = {
  jobChoices: ["Why this job?", "काम का कारण", "कामाचे कारण"],
  help: ["Get help", "मदद लें", "मदत घ्या"],
  money: ["My money", "मेरी कमाई", "माझी कमाई"],
  ideas: ["Share an idea", "सुझाव दें", "कल्पना सांगा"],
  votes: ["Our votes", "हमारा वोट", "आपले मत"],
  more: ["More details", "और जानकारी", "अधिक माहिती"],
  sharingRules: ["How our rules share work", "हमारे नियम काम कैसे बांटते हैं", "आपले नियम काम कसे वाटतात"],
  workRules: ["Our work rules", "हमारे काम के नियम", "आपल्या कामाचे नियम"],
  close: ["Close", "बंद करें", "बंद करा"],
  back: ["Go back", "वापस जाएँ", "मागे जा"],
  send: ["Send request", "अनुरोध भेजें", "विनंती पाठवा"],
  optional: ["Tell us more (optional)", "कुछ और बताएं (ज़रूरी नहीं)", "आणखी सांगा (ऐच्छिक)"],
  noPenalty: ["Asking for help will not lower your rating or reduce future job offers.", "मदद मांगने से आपकी रेटिंग या आगे मिलने वाले काम कम नहीं होंगे।", "मदत मागितल्यामुळे तुमचे रेटिंग किंवा पुढे मिळणारी कामे कमी होणार नाहीत."],
  pay: ["My pay", "मेरा भुगतान", "माझे पैसे"],
  safety: ["I feel unsafe", "मुझे खतरा लग रहा है", "मला धोका वाटतोय"],
  scope: ["Extra work", "ज़्यादा काम", "अतिरिक्त काम"],
  travel: ["Travel problem", "आने-जाने की परेशानी", "प्रवासाची अडचण"],
  interaction: ["Customer problem", "ग्राहक से परेशानी", "ग्राहकाची अडचण"],
  other: ["Something else", "कुछ और", "दुसरे काही"],
  fairIntro: ["See why a job was given to you or to another member.", "देखें कि काम आपको या दूसरे सदस्य को क्यों मिला।", "काम तुम्हाला किंवा दुसऱ्या सदस्याला का मिळाले ते पहा."],
  allJobs: ["All jobs", "सभी काम", "सर्व कामे"],
  missedJobs: ["Jobs I didn’t get", "जो काम मुझे नहीं मिले", "मला न मिळालेली कामे"],
  noJobs: ["No job decisions yet", "अभी काम का कोई फैसला नहीं", "अजून कामाचा निर्णय नाही"],
  noJobsHelp: ["After a job is assigned, its reason will appear here.", "काम मिलने के बाद उसका कारण यहाँ दिखेगा।", "काम दिल्यानंतर त्याचे कारण येथे दिसेल."],
  noMissedJobs: ["No missed jobs in your saved records.", "आपके रिकॉर्ड में छूटा हुआ काम नहीं है।", "तुमच्या नोंदीत न मिळालेले काम नाही."],
  noChecks: ["You have not asked for a job check yet.", "आपने अभी काम की जांच नहीं मांगी है।", "तुम्ही अजून कामाची तपासणी मागितलेली नाही."],
  wonJob: ["You got this job.", "यह काम आपको मिला।", "हे काम तुम्हाला मिळाले."],
  missedJob: ["This job went to {name}.", "यह काम {name} को मिला।", "हे काम {name} यांना मिळाले."],
  lessWorkYou: ["You had less work booked, so it was your turn.", "आपके पास कम काम था, इसलिए आपकी बारी आई।", "तुमच्याकडे कमी काम होते, म्हणून तुमची पाळी आली."],
  lessWorkThem: ["They had less work booked, so it was their turn.", "उनके पास कम काम था, इसलिए उनकी बारी आई।", "त्यांच्याकडे कमी काम होते, म्हणून त्यांची पाळी आली."],
  sameWork: ["Both members had the same amount of work. The fixed tie rule decided the job.", "दोनों के पास बराबर काम था। पहले से तय नियम ने काम दिया।", "दोघांकडे सारखे काम होते. आधी ठरलेल्या नियमानुसार काम दिले."],
  onlyMember: ["You were the only member available with the skills and safe working hours this job needed.", "इस काम के हुनर और सुरक्षित समय के साथ सिर्फ आप उपलब्ध थे।", "या कामाचे कौशल्य आणि सुरक्षित वेळ असलेले फक्त तुम्ही उपलब्ध होता."],
  safetyHelp: ["If you feel unsafe, pause work and move to a safe place before sending this request.", "खतरा लगे तो काम रोकें और सुरक्षित जगह जाकर अनुरोध भेजें।", "धोका वाटल्यास काम थांबवा आणि सुरक्षित ठिकाणी जाऊन विनंती पाठवा."],
  checkJob: ["Ask to check this job", "इस काम की जांच करवाएं", "या कामाची तपासणी मागा"],
  checkHeading: ["What should we check?", "क्या जांचना चाहिए?", "काय तपासायचे आहे?"],
  checkIntro: ["Your cooperative will check the saved job record.", "आपकी सहकारी संस्था काम का पुराना रिकॉर्ड जांचेगी।", "तुमची सहकारी संस्था जतन केलेली कामाची नोंद तपासेल."],
  job: ["Choose a job", "काम चुनें", "काम निवडा"],
  jobOrder: ["Who got the job", "काम किसको मिला", "काम कोणाला मिळाले"],
  workHours: ["My work hours", "मेरे काम के घंटे", "माझे कामाचे तास"],
  skills: ["My skills", "मेरा हुनर", "माझे कौशल्य"],
  coop: ["Another cooperative", "दूसरी सहकारी संस्था", "दुसरी सहकारी संस्था"],
  savedRecord: ["Saved job record", "काम का जतन किया रिकॉर्ड", "कामाची जतन केलेली नोंद"],
  checkSent: ["Request sent. Your cooperative will check this job.", "अनुरोध भेजा गया। आपकी सहकारी संस्था इस काम की जांच करेगी।", "विनंती पाठवली. तुमची सहकारी संस्था हे काम तपासेल."],
  checks: ["Your job checks", "आपकी जांच की स्थिति", "तुमच्या तपासणीची स्थिती"],
  received: ["Request received", "अनुरोध मिला", "विनंती मिळाली"],
  checked: ["Job record checked", "काम का रिकॉर्ड जांचा गया", "कामाची नोंद तपासली"],
  confirmed: ["The rule was followed", "नियम का पालन हुआ", "नियम पाळला गेला"],
  violation: ["A mistake was found", "गलती मिली", "चूक आढळली"],
  humanReview: ["A person will review this", "व्यक्ति जांच करेगा", "व्यक्ती तपासणी करेल"],
  remedied: ["Action recorded", "कार्रवाई दर्ज हुई", "कारवाई नोंदवली"],
  closed: ["Closed", "बंद", "बंद"],
  response: ["Cooperative reply", "सहकारी संस्था का जवाब", "सहकारी संस्थेचे उत्तर"],
  nextCheck: ["Waiting for the cooperative to check the job.", "सहकारी संस्था की जांच का इंतज़ार है।", "सहकारी संस्थेच्या तपासणीची वाट पाहत आहे."],
  helpIntro: ["What do you need help with?", "किस बात में मदद चाहिए?", "कशासाठी मदत हवी आहे?"],
  helpNote: ["Choose a problem. Your cooperative will receive your request.", "परेशानी चुनें। आपका अनुरोध सहकारी संस्था को जाएगा।", "अडचण निवडा. तुमची विनंती सहकारी संस्थेला जाईल."],
  relatedJob: ["Which job is this about?", "यह किस काम के बारे में है?", "हे कोणत्या कामाबद्दल आहे?"],
  general: ["Not about one job", "किसी एक काम के बारे में नहीं", "एका कामाबद्दल नाही"],
  describeHelp: ["For example: I have not received my pay.", "जैसे: मुझे मेरे पैसे नहीं मिले।", "उदा. माझे पैसे मिळाले नाहीत."],
  helpSent: ["Request sent. You can follow it below.", "अनुरोध भेजा गया। नीचे उसकी स्थिति देखें।", "विनंती पाठवली. खाली तिची स्थिती पहा."],
  requests: ["Your help requests", "आपके मदद के अनुरोध", "तुमच्या मदतीच्या विनंत्या"],
  noRequests: ["You have no help requests yet.", "अभी मदद का कोई अनुरोध नहीं है।", "अजून मदतीची विनंती नाही."],
  updated: ["Update added", "नई जानकारी जोड़ी गई", "नवीन माहिती जोडली"],
  addInfo: ["Add more information", "और जानकारी जोड़ें", "अधिक माहिती जोडा"],
  sendInfo: ["Send information", "जानकारी भेजें", "माहिती पाठवा"],
  helpStatus: ["The cooperative has received this request.", "सहकारी संस्था को यह अनुरोध मिल गया है।", "सहकारी संस्थेला ही विनंती मिळाली आहे."],
  ideasIntro: ["What could make work better?", "काम कैसे बेहतर हो सकता है?", "काम आणखी चांगले कसे होईल?"],
  ideasNote: ["Share one idea in your own words. Members can discuss it.", "अपने शब्दों में एक सुझाव दें। सदस्य उस पर बात कर सकते हैं।", "तुमच्या शब्दांत एक कल्पना सांगा. सदस्य त्यावर चर्चा करू शकतात."],
  ideaAbout: ["What is your idea about?", "सुझाव किस बारे में है?", "कल्पना कशाबद्दल आहे?"],
  payIdea: ["Better pay", "बेहतर भुगतान", "चांगला मोबदला"],
  jobsIdea: ["Sharing jobs", "काम बांटना", "काम वाटप"],
  safetyIdea: ["Safer work", "सुरक्षित काम", "सुरक्षित काम"],
  scopeIdea: ["Extra work and charges", "अतिरिक्त काम और पैसे", "अतिरिक्त काम आणि पैसे"],
  accessIdea: ["Getting more work", "ज़्यादा काम मिलना", "अधिक काम मिळणे"],
  ideaWords: ["Tell us your idea", "अपना सुझाव बताएं", "तुमची कल्पना सांगा"],
  ideaHint: ["For example: Please allow more rest between jobs.", "जैसे: दो कामों के बीच आराम के लिए ज़्यादा समय दें।", "उदा. दोन कामांमध्ये विश्रांतीसाठी अधिक वेळ द्या."],
  ideaLength: ["Write a short sentence (at least 10 characters).", "एक छोटा वाक्य लिखें (कम से कम 10 अक्षर)।", "एक लहान वाक्य लिहा (किमान 10 अक्षरे)."],
  sendIdea: ["Send my idea", "मेरा सुझाव भेजें", "माझी कल्पना पाठवा"],
  ideaSent: ["Idea sent. You can follow it below.", "सुझाव भेजा गया। नीचे उसकी स्थिति देखें।", "कल्पना पाठवली. खाली तिची स्थिती पहा."],
  myIdeas: ["Your ideas", "आपके सुझाव", "तुमच्या कल्पना"],
  noIdeas: ["No ideas sent yet.", "अभी कोई सुझाव नहीं भेजा।", "अजून कल्पना पाठवली नाही."],
  sent: ["Sent", "भेजा गया", "पाठवली"],
  reading: ["Being reviewed", "विचार हो रहा है", "विचार सुरू आहे"],
  acceptedIdea: ["Chosen for discussion", "चर्चा के लिए चुना गया", "चर्चेसाठी निवडली"],
  declinedIdea: ["Not taken forward", "आगे नहीं बढ़ाया गया", "पुढे नेली नाही"],
  ideaProcess: ["Sending an idea does not change the rules. Members must review and vote first.", "सुझाव भेजने से नियम नहीं बदलते। पहले सदस्य जांचते हैं और वोट देते हैं।", "कल्पना पाठवल्याने नियम बदलत नाहीत. आधी सदस्य तपासतात आणि मत देतात."],
  moneyIntro: ["See what you have earned and where it came from.", "देखें कितनी कमाई हुई और किस काम से हुई।", "किती कमाई झाली आणि कोणत्या कामातून झाली ते पहा."],
  moneyTotal: ["Total recorded earnings", "दर्ज कुल कमाई", "नोंदवलेली एकूण कमाई"],
  demoMoney: ["Demo amounts: sample history plus payments recorded in this demo.", "डेमो राशि: पुराने नमूने और इस डेमो में दर्ज भुगतान।", "डेमो रक्कम: जुने नमुने आणि या डेमोत नोंदवलेली देयके."],
  paidJobs: ["Paid jobs", "भुगतान वाले काम", "पैसे मिळालेली कामे"],
  cancelMoney: ["Pay for cancelled jobs", "रद्द कामों के पैसे", "रद्द कामांचे पैसे"],
  payments: ["Recent payments", "हाल के भुगतान", "अलीकडची देयके"],
  workPayment: ["Payment for {service}", "{service} के पैसे", "{service}चे पैसे"],
  cancellationPayment: ["Pay for a cancelled job", "रद्द काम के पैसे", "रद्द कामाचे पैसे"],
  sample: ["Sample record", "नमूना रिकॉर्ड", "नमुना नोंद"],
  live: ["Recorded in this demo", "इस डेमो में दर्ज", "या डेमोत नोंदवलेले"],
  noPayments: ["No payments recorded yet.", "अभी कोई भुगतान दर्ज नहीं है।", "अजून देयकाची नोंद नाही."],
  allPayments: ["See all payments", "सभी भुगतान देखें", "सर्व देयके पहा"],
  breakdown: ["Where my money came from", "मेरी कमाई कहाँ से हुई", "माझी कमाई कुठून झाली"],
  completedWork: ["Completed work", "पूरा हुआ काम", "पूर्ण झालेले काम"],
  unpaid: ["Jobs not paid yet", "जिन कामों के पैसे बाकी हैं", "पैसे बाकी असलेली कामे"],
  unpaidNote: ["These jobs are not included in your earnings yet.", "इन कामों के पैसे अभी कुल कमाई में नहीं जुड़े हैं।", "या कामांचे पैसे अजून एकूण कमाईत जोडलेले नाहीत."],
  votesIntro: ["Help decide our work rules.", "हमारे काम के नियम तय करने में भाग लें।", "आपल्या कामाचे नियम ठरवण्यात भाग घ्या."],
  rulesChange: ["A change to our work rules", "हमारे काम के नियमों में बदलाव", "आपल्या कामाच्या नियमांत बदल"],
  votesNote: ["Read the change. Then choose yes or no. Each member has one vote.", "बदलाव पढ़ें। फिर हाँ या नहीं चुनें। हर सदस्य का एक वोट है।", "बदल वाचा. मग हो किंवा नाही निवडा. प्रत्येक सदस्याचे एक मत आहे."],
  noVote: ["No vote is open right now.", "अभी वोट देने के लिए कोई प्रस्ताव नहीं है।", "सध्या मत देण्यासाठी प्रस्ताव नाही."],
  now: ["Now", "अभी", "आता"],
  ifApproved: ["If members approve", "सदस्य मंज़ूर करें तो", "सदस्यांनी मंजूर केल्यास"],
  minPay: ["Minimum pay for new jobs", "नए काम का न्यूनतम भुगतान", "नवीन कामाचा किमान मोबदला"],
  payIncrease: ["The minimum pay for a new job would rise by ₹{amount}.", "नए काम का न्यूनतम भुगतान ₹{amount} बढ़ेगा।", "नवीन कामाचा किमान मोबदला ₹{amount} वाढेल."],
  paySame: ["The minimum pay would stay the same.", "न्यूनतम भुगतान उतना ही रहेगा।", "किमान मोबदला तसाच राहील."],
  payDecrease: ["The proposed minimum pay is ₹{amount} lower. Review this carefully.", "प्रस्तावित न्यूनतम भुगतान ₹{amount} कम है। ध्यान से देखें।", "सुचवलेला किमान मोबदला ₹{amount} कमी आहे. काळजीपूर्वक पहा."],
  pastUnchanged: ["This is a proposal. It will not change money or job records from the past.", "यह प्रस्ताव है। पिछले भुगतान और काम के रिकॉर्ड नहीं बदलेंगे।", "हा प्रस्ताव आहे. आधीचे पैसे आणि कामाच्या नोंदी बदलणार नाहीत."],
  understood: ["I understand. Show voting", "मैं समझ गया/गई। वोट दिखाएं", "मला समजले. मतदान दाखवा"],
  choice: ["Do you agree with this change?", "क्या आप इस बदलाव से सहमत हैं?", "तुम्ही या बदलाशी सहमत आहात का?"],
  yes: ["Yes, I agree", "हाँ, मैं सहमत हूँ", "हो, मी सहमत आहे"],
  no: ["No, I disagree", "नहीं, मैं सहमत नहीं हूँ", "नाही, मी सहमत नाही"],
  whyNo: ["Why do you disagree?", "आप सहमत क्यों नहीं हैं?", "तुम्ही सहमत का नाही?"],
  whyNoHint: ["Tell members your reason in a few words.", "कुछ शब्दों में सदस्यों को कारण बताएं।", "काही शब्दांत सदस्यांना कारण सांगा."],
  confirmYes: ["Confirm my yes vote", "मेरा हाँ वोट दर्ज करें", "माझे हो मत नोंदवा"],
  confirmNo: ["Confirm my no vote", "मेरा नहीं वोट दर्ज करें", "माझे नाही मत नोंदवा"],
  voteRecorded: ["Your vote is recorded", "आपका वोट दर्ज है", "तुमचे मत नोंदवले आहे"],
  voteOnce: ["You have voted once. Your answer is saved.", "आपने एक बार वोट दिया है। आपका जवाब जतन है।", "तुम्ही एकदा मत दिले आहे. तुमचे उत्तर जतन आहे."],
  participation: ["{count} members have voted. At least 9 must take part and 7 must agree before this rule can start.", "{count} सदस्यों ने वोट दिया। नियम शुरू होने से पहले कम से कम 9 सदस्य वोट दें और 7 सहमत हों।", "{count} सदस्यांनी मत दिले. नियम सुरू होण्याआधी किमान 9 सदस्यांनी मत द्यावे आणि 7 जण सहमत असावेत."],
  voteResult: ["{count} members voted: {yes} agreed and {no} disagreed.", "{count} सदस्यों ने वोट दिया: {yes} सहमत और {no} असहमत।", "{count} सदस्यांनी मत दिले: {yes} सहमत आणि {no} असहमत."],
  voteSent: ["Your vote is saved.", "आपका वोट जतन है।", "तुमचे मत जतन आहे."],
  readyVote: ["You can now choose yes or no.", "अब हाँ या नहीं चुन सकते हैं।", "आता हो किंवा नाही निवडू शकता."],
  ruleActive: ["Members approved this rule. It is now in use.", "सदस्यों ने नियम मंज़ूर किया। यह अब लागू है।", "सदस्यांनी नियम मंजूर केला. आता तो वापरात आहे."],
  beforeChange: ["Before the change", "बदलाव से पहले", "बदलाआधी"],
  approvedRule: ["Approved rule", "मंज़ूर नियम", "मंजूर नियम"],
  voteClosed: ["Voting has ended for this proposal.", "इस प्रस्ताव पर मतदान खत्म हुआ।", "या प्रस्तावाचे मतदान संपले."],
  moreVote: ["Full proposal and vote count", "पूरा प्रस्ताव और वोट की गिनती", "पूर्ण प्रस्ताव आणि मतांची संख्या"],
  waitChange: ["Extra customer wait allowed when sharing work: {before} minutes now, {after} minutes if approved.", "काम बांटने के लिए ग्राहक का अतिरिक्त इंतज़ार: अभी {before} मिनट, मंज़ूर होने पर {after} मिनट।", "काम वाटताना ग्राहकाला अतिरिक्त वाट पाहण्याची मर्यादा: आता {before} मिनिटे, मंजूर झाल्यास {after} मिनिटे."],
  electrician: ["Electrical work", "बिजली का काम", "विजेचे काम"],
  plumbing: ["Plumbing", "नल का काम", "नळाचे काम"],
  cleaning: ["Cleaning", "सफाई", "साफसफाई"],
  appliance: ["Appliance repair", "उपकरण की मरम्मत", "उपकरण दुरुस्ती"],
  carpentry: ["Carpentry", "बढ़ई का काम", "सुतारकाम"],
  jobWork: ["Service work", "सेवा का काम", "सेवेचे काम"],
} as const;

export type WorkerCopyKey = keyof typeof phrases;
export function workerText(locale: Locale, key: WorkerCopyKey, params: Record<string, string | number> = {}) {
  const text: string = phrases[key][locale === "hi" ? 1 : locale === "mr" ? 2 : 0];
  return text.replace(/\{(\w+)\}/g, (_, name: string) => String(params[name] ?? `{${name}}`));
}
export function workerService(locale: Locale, service: string) {
  return workerText(locale, ["electrician", "plumbing", "cleaning", "appliance", "carpentry"].includes(service) ? service as WorkerCopyKey : "jobWork");
}
export function workerStatus(locale: Locale, status: string) {
  const keys: Record<string, WorkerCopyKey> = {
    open: "received", responded: "updated", closed: "closed", submitted: "sent",
    "under-review": "reading", accepted: "acceptedIdea", declined: "declinedIdea",
    replayed: "checked", confirmed: "confirmed", violation: "violation",
    "human-review": "humanReview", remedied: "remedied", upheld: "violation", dismissed: "confirmed",
  };
  return workerText(locale, keys[status] ?? "reading");
}
