import type { Locale } from "./domain.ts";

// Whole phrases in each language; stored categories and decision facts stay unchanged.
const phrases = {
  jobChoices: ["Why this job?", "काम का कारण", "कामाचे कारण"],
  jobRecord: ["Job number", "काम नंबर", "काम क्रमांक"],
  help: ["Get help", "मदद लें", "मदत घ्या"],
  money: ["My money", "मेरी कमाई", "माझी कमाई"],
  ideas: ["Share an idea", "सुझाव दें", "कल्पना सांगा"],
  votes: ["Our votes", "हमारा वोट", "आपले मत"],
  simplePayQuestion: ["Raise minimum job pay?", "काम का न्यूनतम भुगतान बढ़ाएं?", "कामाचा किमान मोबदला वाढवायचा?"],
  simpleRuleQuestion: ["Change our work rules?", "हमारे काम के नियम बदलें?", "आपल्या कामाचे नियम बदलायचे?"],
  simpleSavedHeading: ["Your vote is saved", "आपका वोट दर्ज है", "तुमचे मत जतन आहे"],
  simpleActiveHeading: ["Our new pay rule", "हमारा नया भुगतान नियम", "आपला नवा मोबदला नियम"],
  simpleClosedHeading: ["Vote update", "वोट की स्थिति", "मतदानाची स्थिती"],
  simplePayGain: ["₹{amount} more on jobs at the minimum.", "न्यूनतम राशि वाले काम में ₹{amount} ज़्यादा।", "किमान रकमेच्या कामात ₹{amount} जास्त."],
  simpleJobChange: ["Original pay for your {service}: {before} would become {after}.", "आपके {service} में पहले {before} तय थे। इस नियम से {after} होंगे।", "तुमच्या {service} सुरुवातीला {before} ठरले होते. या नियमाने {after} होतील."],
  simpleJobSame: ["Your {service} already pays {before}. That amount would stay the same.", "आपके {service} में पहले से {before} तय हैं। वह राशि उतनी ही रहेगी।", "तुमच्या {service} आधीच {before} ठरले आहेत. ती रक्कम कायम राहील."],
  exampleElectrician: ["electrical work", "बिजली के काम", "विजेच्या कामासाठी"],
  examplePlumbing: ["plumbing", "नल के काम", "नळाच्या कामासाठी"],
  exampleCleaning: ["cleaning", "सफाई के काम", "साफसफाईसाठी"],
  exampleAppliance: ["appliance repair", "उपकरण की मरम्मत", "उपकरण दुरुस्तीसाठी"],
  exampleCarpentry: ["carpentry", "बढ़ई के काम", "सुतारकामासाठी"],
  exampleService: ["service work", "सेवा के काम", "सेवेच्या कामासाठी"],
  simpleNoJob: ["No saved job example yet. New jobs would start at {amount}; this does not guarantee a job.", "अभी काम का दर्ज उदाहरण नहीं है। नया काम {amount} से शुरू होगा; काम मिलने की गारंटी नहीं है।", "कामाचे जतन उदाहरण अजून नाही. नवीन काम {amount} पासून सुरू होईल; काम मिळण्याची हमी नाही."],
  simplePreviewNote: ["Example only, before costs. Old pay stays the same.", "खर्च से पहले का उदाहरण है। पुराना भुगतान नहीं बदलता।", "खर्चाआधीचे उदाहरण आहे. जुना मोबदला बदलत नाही."],
  simpleDetails: ["Check the details", "पूरी जानकारी देखें", "पूर्ण माहिती पहा"],
  simpleYourJobs: ["Your saved jobs", "आपके दर्ज काम", "तुमची जतन कामे"],
  simpleCooperativeJobs: ["Jobs used in the comparison", "तुलना में इस्तेमाल किए काम", "तुलनेत वापरलेली कामे"],
  simpleUnchanged: ["What stays the same", "क्या नहीं बदलता", "काय बदलत नाही"],
  simpleOtherSetting: ["Other setting in this proposal", "प्रस्ताव में दूसरा बदलाव", "प्रस्तावातील दुसरा बदल"],
  simpleHowVoteWorks: ["How the vote works", "वोट से नियम कैसे बदलता है", "मतदानाने नियम कसा बदलतो"],
  simpleFullProposal: ["Full proposal record", "प्रस्ताव का पूरा रिकॉर्ड", "प्रस्तावाची पूर्ण नोंद"],
  simpleUnderstand: ["I understand this change", "मुझे यह बदलाव समझ में आया", "मला हा बदल समजला आहे"],
  simpleSaveVote: ["Save my vote", "मेरा वोट दर्ज करें", "माझे मत नोंदवा"],
  simpleChoose: ["Choose Yes or No.", "हाँ या नहीं चुनें।", "हो किंवा नाही निवडा."],
  simpleReadFirst: ["Read or listen, then tick ‘I understand’.", "पढ़ें या सुनें, फिर ‘समझ में आया’ पर निशान लगाएं।", "वाचा किंवा ऐका, मग ‘मला समजले’ वर खूण करा."],
  simpleVoteOnce: ["One vote per member. You cannot change a saved vote.", "हर सदस्य का एक वोट। दर्ज वोट बदल नहीं सकते।", "प्रत्येक सदस्याचे एक मत. जतन मत बदलता येत नाही."],
  simpleSeeChange: ["See the pay change and details", "भुगतान का बदलाव और जानकारी देखें", "मोबदल्याचा बदल आणि माहिती पहा"],
  simpleVotedCount: ["{count} members have voted.", "{count} सदस्यों ने वोट दिया है।", "{count} सदस्यांनी मत दिले आहे."],
  simpleMyYes: ["You voted Yes.", "आपने हाँ कहा।", "तुम्ही हो मत दिले."],
  simpleMyNo: ["You voted No.", "आपने नहीं कहा।", "तुम्ही नाही मत दिले."],
  simpleOneMemberNeeded: ["One more member needs to vote.", "एक और सदस्य का वोट चाहिए।", "आणखी एका सदस्याचे मत हवे."],
  simpleMembersNeeded: ["{count} more members need to vote.", "{count} और सदस्यों के वोट चाहिए।", "आणखी {count} सदस्यांची मते हवीत."],
  simpleOneYesNeeded: ["One more Yes vote is needed.", "एक और हाँ का वोट चाहिए।", "आणखी एक हो मत हवे."],
  simpleYesNeeded: ["{count} more Yes votes are needed.", "{count} और हाँ के वोट चाहिए।", "आणखी {count} हो मते हवीत."],
  simpleNewJobPay: ["Your new job has agreed pay of ₹{amount} under this rule.", "इस नियम से आपके नए काम का तय भुगतान ₹{amount} है।", "या नियमानुसार तुमच्या नवीन कामाचा ठरलेला मोबदला ₹{amount} आहे."],
  ballotResultHeading: ["Vote update", "वोट की स्थिति", "मतदानाची स्थिती"],
  ballotMembers: ["Members voted", "सदस्यों ने वोट दिया", "सदस्यांनी मत दिले"],
  ballotYes: ["Yes votes", "हाँ के वोट", "हो मते"],
  ballotNo: ["No votes", "नहीं के वोट", "नाही मते"],
  ballotRequirements: ["At least {participants} members must vote and {support} must agree.", "कम से कम {participants} सदस्य वोट दें और {support} सहमत हों।", "किमान {participants} सदस्यांनी मत द्यावे आणि {support} जण सहमत असावेत."],
  ballotNeedMembers: ["More members needed to vote: {count}.", "अभी और सदस्य वोट दें: {count}।", "अजून मत देणारे सदस्य हवे: {count}."],
  ballotNeedYes: ["More yes votes needed: {count}.", "अभी और हाँ के वोट चाहिए: {count}।", "अजून हो मते हवीत: {count}."],
  ballotWaiting: ["Voting is open. Current minimum: ₹{amount}.", "मतदान चल रहा है। अभी न्यूनतम: ₹{amount}।", "मतदान सुरू आहे. सध्याची किमान रक्कम: ₹{amount}."],
  ballotReady: ["Enough votes to make the change. It has not started yet. New jobs still start at ₹{amount}.", "बदलाव के लिए ज़रूरी वोट मिल गए। नियम अभी लागू नहीं हुआ। नए काम अभी ₹{amount} से शुरू होते हैं।", "बदलासाठी आवश्यक मते मिळाली. नियम अजून लागू झालेला नाही. नवीन कामे सध्या ₹{amount} पासून सुरू होतात."],
  ballotBlocked: ["This change cannot start because it breaks worker protections. The ₹{amount} minimum stays in use.", "यह बदलाव कामगारों की सुरक्षा तोड़ता है, इसलिए लागू नहीं हो सकता। ₹{amount} न्यूनतम लागू है।", "हा बदल कामगारांचे संरक्षण मोडतो, म्हणून लागू होऊ शकत नाही. ₹{amount} किमान रक्कम लागू आहे."],
  ballotActive: ["Now in use: at least ₹{after} per new job. This is not money already earned.", "अब लागू: नए काम में कम से कम ₹{after}। यह मिली हुई कमाई नहीं है।", "आता लागू: नवीन कामासाठी किमान ₹{after}. ही मिळालेली कमाई नाही."],
  ballotSuperseded: ["A later rule is now in use, with a ₹{amount} minimum. This earlier vote stays saved.", "बाद का नियम अब लागू है; न्यूनतम ₹{amount} है। यह पुराना वोट दर्ज रहता है।", "नंतरचा नियम आता वापरात आहे; किमान रक्कम ₹{amount} आहे. हे आधीचे मत जतन आहे."],
  ballotRejected: ["This proposal was closed without starting the rule. The current ₹{amount} minimum stays in use.", "यह प्रस्ताव नियम लागू किए बिना बंद हुआ। अभी ₹{amount} न्यूनतम लागू है।", "नियम लागू न करता हा प्रस्ताव बंद झाला. सध्या ₹{amount} किमान रक्कम लागू आहे."],
  ballotSimulated: ["This change is not open for voting yet. The current ₹{amount} minimum stays in use.", "इस बदलाव पर अभी मतदान शुरू नहीं हुआ। अभी ₹{amount} न्यूनतम लागू है।", "या बदलावर मतदान अजून सुरू झालेले नाही. सध्या ₹{amount} किमान रक्कम लागू आहे."],
  ballotChoiceNote: ["Yes supports the change. No records your disagreement. One vote alone does not change the rule.", "हाँ से आप बदलाव का समर्थन करते हैं। नहीं से असहमति दर्ज होती है। अकेले एक वोट से नियम नहीं बदलता।", "हो म्हणजे बदलाला पाठिंबा. नाही म्हणजे असहमतीची नोंद. एका मताने एकट्याने नियम बदलत नाही."],
  ballotYesEffect: ["You support ₹{amount} minimum pay. It begins when the cooperative starts the approved rule.", "आप ₹{amount} न्यूनतम का समर्थन करते हैं। संस्था के मंज़ूर नियम लागू करने पर बदलाव होगा।", "तुम्ही ₹{amount} किमान रक्कमेला पाठिंबा देता. संस्थेने मंजूर नियम लागू केल्यावर बदल होईल."],
  ballotNoEffect: ["You disagree. Other members can still approve. ₹{amount} stays until the rule starts.", "आप असहमत हैं। दूसरे सदस्य फिर भी मंज़ूर कर सकते हैं। नियम लागू होने तक ₹{amount} रहेगा।", "तुम्ही असहमत आहात. इतर सदस्य तरीही मंजूर करू शकतात. नियम लागू होईपर्यंत ₹{amount} कायम राहील."],
  ballotYourReason: ["Your saved reason", "आपका दर्ज कारण", "तुमचे जतन कारण"],
  ballotCompareAgain: ["See what this rule changes for you", "देखें इस नियम से आपके लिए क्या बदलेगा", "या नियमाने तुमच्यासाठी काय बदलते ते पहा"],
  twinHeading: ["See what this rule would change", "देखें इस नियम से क्या बदलेगा", "या नियमाने काय बदलेल ते पहा"],
  twinIntro: ["Policy Twin compares the same saved jobs and members under both rules.", "पॉलिसी ट्विन उन्हीं जतन कामों और सदस्यों को दोनों नियमों से तुलना करता है।", "पॉलिसी ट्विन त्याच जतन कामांची आणि सदस्यांची दोन्ही नियमांनुसार तुलना करतो."],
  twinFloorEffect: ["Under this changed rule, new jobs would get at least ₹{after}. Higher agreed pay stays higher.", "इस बदले नियम से नए काम में कम से कम ₹{after} मिलेंगे। पहले से तय ज़्यादा भुगतान उतना ही रहेगा।", "या बदललेल्या नियमाने नवीन कामासाठी किमान ₹{after} मिळतील. आधीच ठरलेला जास्त मोबदला तसाच राहील."],
  twinForYou: ["What it means for you, {name}", "आपके लिए इसका मतलब, {name}", "तुमच्यासाठी याचा अर्थ, {name}"],
  twinOwnJobs: ["Your saved jobs, compared as new offers: {count}.", "आपके जतन कामों की नए प्रस्तावों के रूप में तुलना: {count}।", "तुमच्या जतन कामांची नवीन प्रस्ताव म्हणून तुलना: {count}."],
  twinOldPay: ["Pay under old rule", "पुराने नियम से भुगतान", "जुन्या नियमाने मोबदला"],
  twinNewPay: ["Pay under changed rule", "बदले नियम से भुगतान", "बदललेल्या नियमाने मोबदला"],
  twinDifference: ["Difference in this comparison: {amount}.", "इस तुलना में अंतर: {amount}।", "या तुलनेतील फरक: {amount}."],
  twinNoOwnJobs: ["No complete saved job decision for you yet. A higher minimum helps when you receive a new job; it does not promise you a job.", "अभी आपके लिए पूरा जतन काम का निर्णय नहीं है। नया काम मिलने पर बढ़ी न्यूनतम राशि मदद करती है; इससे काम मिलने की गारंटी नहीं है।", "तुमच्यासाठी पूर्ण जतन कामाचा निर्णय अजून नाही. नवीन काम मिळाल्यावर वाढलेली किमान रक्कम मदत करते; काम मिळण्याची हमी नाही."],
  twinPayBasis: ["Preview of full job pay before costs. This is not earned money. Extras, cancellations and payments are not recalculated.", "खर्च से पहले पूरे काम के भुगतान की तुलना है। यह मिली कमाई नहीं है। अतिरिक्त काम, रद्द काम और पुराने भुगतान फिर नहीं गिने जाते।", "खर्चाआधीच्या पूर्ण कामाच्या मोबदल्याची तुलना आहे. ही मिळालेली कमाई नाही. अतिरिक्त काम, रद्द काम आणि जुने पैसे पुन्हा मोजले जात नाहीत."],
  twinSameOrder: ["Job turns stay the same. Qualified, available members with less booked work still go first.", "काम का क्रम नहीं बदलता। योग्य, उपलब्ध और कम काम वाले सदस्य पहले आते हैं।", "कामाचा क्रम बदलत नाही. पात्र, उपलब्ध आणि कमी काम असलेले सदस्य आधी येतात."],
  twinSameSafety: ["Your work limit, safe decline and rating protection stay unchanged.", "काम की सीमा, सुरक्षित नकार और रेटिंग की सुरक्षा नहीं बदलती।", "कामाची मर्यादा, सुरक्षित नकार आणि रेटिंगचे संरक्षण बदलत नाही."],
  twinEvidence: ["See the saved jobs used in this comparison", "इस तुलना में इस्तेमाल किए काम देखें", "या तुलनेत वापरलेली जतन कामे पहा"],
  twinCooperativeBasis: ["Saved decisions from your cooperative: {count}. Different pay in this preview: {changed}. The quoted job and saved member facts stay the same.", "आपकी सहकारी संस्था के जतन निर्णय: {count}। इस तुलना में बदला भुगतान: {changed}। तय काम और सदस्य की जतन जानकारी एक जैसी रहती है।", "तुमच्या सहकारी संस्थेतील जतन निर्णय: {count}. या तुलनेत बदललेला मोबदला: {changed}. ठरलेले काम आणि सदस्याची जतन माहिती तीच राहते."],
  twinExcluded: ["{count} bookings were left out because a complete matching decision record was not available.", "पूरा सही निर्णय रिकॉर्ड उपलब्ध न होने से {count} काम तुलना में नहीं जोड़े गए।", "पूर्ण जुळणारी निर्णय नोंद उपलब्ध नसल्याने {count} कामे तुलनेत घेतली नाहीत."],
  twinEmpty: ["No complete saved decisions to compare yet. Book a service to see a real job here.", "अभी तुलना के लिए पूरे जतन निर्णय नहीं हैं। यहां असली काम देखने के लिए सेवा बुक करें।", "तुलनेसाठी पूर्ण जतन निर्णय अजून नाहीत. येथे प्रत्यक्ष काम पाहण्यासाठी सेवा बुक करा."],
  twinWait: ["Extra-wait setting: {before} minutes before, {after} minutes after.", "अतिरिक्त इंतज़ार की सीमा: पहले {before} मिनट, बाद में {after} मिनट।", "अतिरिक्त प्रतीक्षेची मर्यादा: आधी {before} मिनिटे, नंतर {after} मिनिटे."],
  twinWaitLimit: ["This setting is stored. The demo does not use it to change job selection or calculate travel times.", "यह सीमा दर्ज होती है। डेमो इससे काम का चयन या यात्रा का समय नहीं बदलता।", "ही मर्यादा नोंदवली जाते. डेमोत यामुळे कामाची निवड किंवा प्रवासाचा वेळ बदलत नाही."],
  twinSpokenImpact: ["On your {count} saved jobs, compared as new offers, full job pay is {before} rupees under the current rule and {after} rupees under the change. This is a preview, not money already earned.", "आपके {count} जतन कामों को नए प्रस्ताव मानें तो पूरे काम का भुगतान अभी के नियम में {before} रुपये और बदलाव में {after} रुपये है। यह तुलना है, पहले से मिली कमाई नहीं।", "तुमच्या {count} जतन कामांना नवीन प्रस्ताव मानल्यास पूर्ण मोबदला सध्याच्या नियमाने {before} रुपये आणि बदलाने {after} रुपये आहे. ही तुलना आहे, आधीच मिळालेली कमाई नाही."],
  more: ["More details", "और जानकारी", "अधिक माहिती"],
  sharingRules: ["How our rules share work", "हमारे नियम काम कैसे बांटते हैं", "आपले नियम काम कसे वाटतात"],
  workRules: ["Our work rules", "हमारे काम के नियम", "आपल्या कामाचे नियम"],
  listen: ["Listen", "सुनें", "ऐका"],
  stopListening: ["Stop listening", "सुनना बंद करें", "ऐकणे थांबवा"],
  readSummary: ["Read the summary", "सारांश पढ़ें", "सारांश वाचा"],
  voiceUnavailable: ["Audio could not play on this device. Read the summary below.", "इस डिवाइस पर आवाज़ नहीं चल सकी। नीचे सारांश पढ़ें।", "या उपकरणावर आवाज ऐकवता आला नाही. खाली सारांश वाचा."],
  voiceMissing: ["A voice for this language is not available on this device. Read the summary below or choose another language.", "इस डिवाइस पर इस भाषा की आवाज़ उपलब्ध नहीं है। नीचे सारांश पढ़ें या दूसरी भाषा चुनें।", "या उपकरणावर या भाषेचा आवाज उपलब्ध नाही. खाली सारांश वाचा किंवा दुसरी भाषा निवडा."],
  spokenMoney: ["{name}, your recorded demo earnings are {amount} rupees.", "{name}, डेमो में आपकी दर्ज कुल कमाई {amount} रुपये है।", "{name}, डेमोत तुमची नोंदवलेली एकूण कमाई {amount} रुपये आहे."],
  spokenJob: ["Your current job is {service}. The agreed pay is {amount} rupees.", "आपका अभी का काम {service} है। तय भुगतान {amount} रुपये है।", "तुमचे सध्याचे काम {service} आहे. ठरलेला मोबदला {amount} रुपये आहे."],
  spokenPayments: ["You have {count} paid jobs. Pay for cancelled jobs is {protection} rupees. Completed jobs awaiting payment total {pending} rupees; they are not included yet.", "आपके {count} कामों के पैसे मिले हैं। रद्द कामों के पैसे {protection} रुपये हैं। पूरे हुए कामों का {pending} रुपये भुगतान बाकी है; वह अभी कुल में नहीं जुड़ा है।", "तुमच्या {count} कामांचे पैसे मिळाले आहेत. रद्द कामांचे पैसे {protection} रुपये आहेत. पूर्ण कामांचे {pending} रुपये मिळायचे आहेत; ते अजून एकूण कमाईत नाहीत."],
  spokenRule: ["Members changed minimum job pay from {before} to {after} rupees. {count} members voted. The approved rule applies to new bookings; older job records stay unchanged.", "सदस्यों ने न्यूनतम भुगतान {before} से {after} रुपये किया। {count} सदस्यों ने वोट दिया। मंज़ूर नियम नए कामों पर लागू है; पुराने रिकॉर्ड नहीं बदलते।", "सदस्यांनी किमान मोबदला {before} वरून {after} रुपये केला. {count} सदस्यांनी मत दिले. मंजूर नियम नवीन कामांना लागू आहे; जुन्या नोंदी बदलत नाहीत."],
  spokenProposal: ["Members are voting on minimum job pay of {after} rupees. The current minimum is {before} rupees. This change is not active yet.", "सदस्य {after} रुपये न्यूनतम भुगतान पर वोट दे रहे हैं। अभी न्यूनतम {before} रुपये है। बदलाव अभी लागू नहीं है।", "सदस्य {after} रुपये किमान मोबदल्यावर मत देत आहेत. सध्या किमान {before} रुपये आहे. बदल अजून लागू झालेला नाही."],
  spokenChecks: ["You have {count} saved job checks.", "आपके काम की जांच के {count} रिकॉर्ड हैं।", "तुमच्या कामाच्या तपासणीच्या {count} नोंदी आहेत."],
  spokenRequests: ["You have {count} open help requests.", "आपके {count} मदद के अनुरोध खुले हैं।", "तुमच्या मदतीच्या {count} विनंत्या सुरू आहेत."],
  currentJob: ["Your current job", "आपका अभी का काम", "तुमचे सध्याचे काम"],
  agreedPay: ["Agreed job pay", "काम का तय भुगतान", "कामाचा ठरलेला मोबदला"],
  nextAction: ["What happens next", "अब क्या करना है", "पुढे काय करायचे"],
  acceptJob: ["Accept job", "काम स्वीकार करें", "काम स्वीकारा"],
  startTravel: ["Start travel", "ग्राहक की ओर चलें", "ग्राहकाकडे निघा"],
  markArrived: ["Mark arrived", "पहुंचने की जानकारी दें", "पोहोचल्याची नोंद करा"],
  addProof: ["Add work proof", "काम का सबूत जोड़ें", "कामाचा पुरावा जोडा"],
  proofAdded: ["Work proof added. The customer can now issue the finish code.", "काम का सबूत जुड़ गया। ग्राहक अब काम पूरा करने का कोड दे सकते हैं।", "कामाचा पुरावा जोडला. ग्राहक आता काम पूर्ण करण्याचा कोड देऊ शकतात."],
  acceptedJob: ["Job accepted.", "काम स्वीकार किया।", "काम स्वीकारले."],
  queueReady: ["No current job. Check the reasons below while you wait.", "अभी कोई काम नहीं है। इंतज़ार करते समय नीचे कारण देखें।", "सध्या काम नाही. वाट पाहताना खाली कारणे पहा."],
  queuePaused: ["You have paused new jobs. Change your work limits when you are ready.", "आपने नए काम रोक रखे हैं। तैयार हों तो काम की सीमा बदलें।", "तुम्ही नवीन कामे थांबवली आहेत. तयार झाल्यावर कामाच्या मर्यादा बदला."],
  whyWaiting: ["Why am I waiting?", "मुझे काम क्यों नहीं मिला?", "मला काम का मिळाले नाही?"],
  mapDirections: ["Map and directions", "नक्शा और रास्ता", "नकाशा आणि मार्ग"],
  jobDetails: ["Job details and progress", "काम की जानकारी और स्थिति", "कामाची माहिती आणि प्रगती"],
  bookedWork: ["Agreed work", "तय काम", "ठरलेले काम"],
  safeDeclineTitle: ["Cannot safely take this job?", "यह काम सुरक्षित रूप से नहीं ले सकते?", "हे काम सुरक्षितपणे घेता येत नाही?"],
  safeDecline: ["Safely decline", "सुरक्षित रूप से मना करें", "सुरक्षितपणे नकार द्या"],
  safeDeclineNote: ["Declining before acceptance has no rating or opportunity penalty.", "स्वीकार करने से पहले मना करने पर रेटिंग या आगे मिलने वाले कामों पर जुर्माना नहीं है।", "स्वीकारण्याआधी नकार दिल्यास रेटिंग किंवा पुढील कामांच्या संधींवर दंड नाही."],
  safeDeclineDone: ["Safe decline recorded. Dispatch ran again without a penalty.", "सुरक्षित नकार दर्ज हुआ। बिना जुर्माने के काम फिर बांटा गया।", "सुरक्षित नकार नोंदवला. दंड न लावता कामाचे पुन्हा वाटप झाले."],
  declineReason: ["Reason", "कारण", "कारण"],
  scopeChange: ["Customer asked for extra work?", "ग्राहक ने ज़्यादा काम मांगा?", "ग्राहकाने अतिरिक्त काम सांगितले?"],
  scopeChangeNote: ["Record extra work before starting it. The customer must approve the new amount first.", "ज़्यादा काम शुरू करने से पहले दर्ज करें। ग्राहक को पहले नया भुगतान मंज़ूर करना होगा।", "अतिरिक्त काम सुरू करण्याआधी नोंदवा. ग्राहकाने आधी नवीन रक्कम मंजूर करायला हवी."],
  extraWork: ["Additional work", "अतिरिक्त काम", "अतिरिक्त काम"],
  extraAmount: ["Added amount", "अतिरिक्त राशि", "अतिरिक्त रक्कम"],
  sendAddition: ["Send addition for approval", "मंज़ूरी के लिए भेजें", "मंजुरीसाठी पाठवा"],
  scopeSent: ["Extra work sent for approval. Wait for the customer's decision.", "ज़्यादा काम मंज़ूरी के लिए भेजा। ग्राहक के फैसले का इंतज़ार करें।", "अतिरिक्त काम मंजुरीसाठी पाठवले. ग्राहकाच्या निर्णयाची वाट पाहा."],
  workLimits: ["My work limits", "मेरे काम की सीमा", "माझ्या कामाच्या मर्यादा"],
  availableJobs: ["Available for new work", "नए काम के लिए उपलब्ध", "नवीन कामासाठी उपलब्ध"],
  maxHours: ["Maximum work today", "आज काम की अधिकतम सीमा", "आज कामाची कमाल मर्यादा"],
  restGap: ["Minimum rest gap", "आराम का न्यूनतम समय", "विश्रांतीचा किमान वेळ"],
  hours: ["{count} hours", "{count} घंटे", "{count} तास"],
  minutes: ["{count} minutes", "{count} मिनट", "{count} मिनिटे"],
  saveLimits: ["Save safety limits", "सुरक्षा की सीमा जतन करें", "सुरक्षेच्या मर्यादा जतन करा"],
  limitsSaved: ["Your work limits are saved for future dispatch.", "आपकी काम की सीमा आगे के कामों के लिए जतन हुई।", "पुढील कामांच्या वाटपासाठी तुमच्या मर्यादा जतन झाल्या."],
  yourVoteChanged: ["Your vote helped change this", "आपके वोट से यह बदलाव हुआ", "तुमच्या मताने हा बदल झाला"],
  membersChanged: ["Members changed our rules", "सदस्यों ने हमारे नियम बदले", "सदस्यांनी आपले नियम बदलले"],
  olderRecordsUnchanged: ["Older job records and earned money stay unchanged.", "पुराने कामों के रिकॉर्ड और मिली कमाई नहीं बदलते।", "जुन्या कामांच्या नोंदी आणि मिळालेली कमाई बदलत नाही."],
  approvedPayChange: ["Minimum job pay changed from ₹{before} to ₹{after}.", "काम का न्यूनतम भुगतान ₹{before} से ₹{after} हुआ।", "कामाचा किमान मोबदला ₹{before} वरून ₹{after} झाला."],
  ruleSupport: ["{count} members voted; {yes} agreed.", "{count} सदस्यों ने वोट दिया; {yes} सहमत थे।", "{count} सदस्यांनी मत दिले; {yes} जण सहमत होते."],
  nextJobRule: ["New bookings use the approved ₹{amount} minimum. This is a minimum, not a payment already earned.", "नए कामों पर मंज़ूर ₹{amount} न्यूनतम लागू है। यह न्यूनतम है, अभी मिली हुई कमाई नहीं।", "नवीन कामांना मंजूर ₹{amount} किमान रक्कम लागू आहे. ही किमान रक्कम आहे, आधीच मिळालेली कमाई नाही."],
  newJobProof: ["Your new job {job} used {rule}, with a ₹{amount} minimum saved in its receipt.", "आपके नए काम {job} में {rule} लागू हुआ; रसीद में ₹{amount} न्यूनतम दर्ज है।", "तुमच्या नवीन काम {job} साठी {rule} वापरला; पावतीत ₹{amount} किमान रक्कम जतन आहे."],
  seeVote: ["See the vote", "वोट देखें", "मतदान पहा"],
  pendingPay: ["Awaiting payment", "भुगतान बाकी है", "पैसे मिळायचे आहेत"],
  checkProgress: ["Request progress", "अनुरोध की स्थिति", "विनंतीची प्रगती"],
  checkReceived: ["Request received", "अनुरोध मिला", "विनंती मिळाली"],
  checkReviewed: ["Saved record checked", "जतन रिकॉर्ड जांचा गया", "जतन नोंद तपासली"],
  checkAnswered: ["Answer recorded", "जवाब दर्ज है", "उत्तर नोंदवले"],
  checkRemedy: ["Correction recorded", "सुधार दर्ज है", "दुरुस्ती नोंदवली"],
  checkWaiting: ["Waiting", "इंतज़ार", "प्रतीक्षा"],
  checkDone: ["Done", "पूरा", "पूर्ण"],
  close: ["Close", "बंद करें", "बंद करा"],
  back: ["Go back", "वापस जाएँ", "मागे जा"],
  send: ["Send request", "अनुरोध भेजें", "विनंती पाठवा"],
  optional: ["Tell us more (optional)", "कुछ और बताएं (ज़रूरी नहीं)", "आणखी सांगा (ऐच्छिक)"],
  noPenalty: ["Asking for help will not lower your rating or reduce future job offers.", "मदद मांगने से आपकी रेटिंग या आगे मिलने वाले काम कम नहीं होंगे।", "मदत मागितल्यामुळे तुमचे रेटिंग किंवा पुढे मिळणारी कामे कमी होणार नाहीत."],
  pay: ["My pay", "मेरा भुगतान", "माझे पैसे"],
  safety: ["I feel unsafe", "मुझे खतरा लग रहा है", "मला धोका वाटतोय"],
  scope: ["Extra work", "ज़्यादा काम", "अतिरिक्त काम"],
  travel: ["Travel problem", "आने-जाने की परेशानी", "प्रवासाची अडचण"],
  interaction: ["Customer problem", "ग्राहक से परेशानी", "ग्राहकाची अडचण"],
  other: ["Something else", "कुछ और", "दुसरे काही"],
  fairIntro: ["See why a job was given to you or to another member.", "देखें कि काम आपको या दूसरे सदस्य को क्यों मिला।", "काम तुम्हाला किंवा दुसऱ्या सदस्याला का मिळाले ते पहा."],
  allJobs: ["All jobs", "सभी काम", "सर्व कामे"],
  missedJobs: ["Jobs I didn’t get", "जो काम मुझे नहीं मिले", "मला न मिळालेली कामे"],
  noJobs: ["No job decisions yet", "अभी काम का कोई फैसला नहीं", "अजून कामाचा निर्णय नाही"],
  noJobsHelp: ["After a job is assigned, its reason will appear here.", "काम मिलने के बाद उसका कारण यहाँ दिखेगा।", "काम दिल्यानंतर त्याचे कारण येथे दिसेल."],
  noMissedJobs: ["No missed jobs in your saved records.", "आपके रिकॉर्ड में छूटा हुआ काम नहीं है।", "तुमच्या नोंदीत न मिळालेले काम नाही."],
  noChecks: ["You have not asked for a job check yet.", "आपने अभी काम की जांच नहीं मांगी है।", "तुम्ही अजून कामाची तपासणी मागितलेली नाही."],
  wonJob: ["You got this job.", "यह काम आपको मिला।", "हे काम तुम्हाला मिळाले."],
  missedJob: ["This job went to {name}.", "यह काम {name} को मिला।", "हे काम {name} यांना मिळाले."],
  lessWorkYou: ["You had less work booked, so it was your turn.", "आपके पास कम काम था, इसलिए आपकी बारी आई।", "तुमच्याकडे कमी काम होते, म्हणून तुमची पाळी आली."],
  lessWorkThem: ["They had less work booked, so it was their turn.", "उनके पास कम काम था, इसलिए उनकी बारी आई।", "त्यांच्याकडे कमी काम होते, म्हणून त्यांची पाळी आली."],
  sameWork: ["Both members had the same amount of work. The fixed tie rule decided the job.", "दोनों के पास बराबर काम था। पहले से तय नियम ने काम दिया।", "दोघांकडे सारखे काम होते. आधी ठरलेल्या नियमानुसार काम दिले."],
  onlyMember: ["You were the only member available with the skills and safe working hours this job needed.", "इस काम के हुनर और सुरक्षित समय के साथ सिर्फ आप उपलब्ध थे।", "या कामाचे कौशल्य आणि सुरक्षित वेळ असलेले फक्त तुम्ही उपलब्ध होता."],
  safetyHelp: ["If you feel unsafe, pause work and move to a safe place before sending this request.", "खतरा लगे तो काम रोकें और सुरक्षित जगह जाकर अनुरोध भेजें।", "धोका वाटल्यास काम थांबवा आणि सुरक्षित ठिकाणी जाऊन विनंती पाठवा."],
  checkJob: ["Ask to check this job", "इस काम की जांच करवाएं", "या कामाची तपासणी मागा"],
  checkHeading: ["What should we check?", "क्या जांचना चाहिए?", "काय तपासायचे आहे?"],
  checkIntro: ["Your cooperative will check the saved job record.", "आपकी सहकारी संस्था काम का पुराना रिकॉर्ड जांचेगी।", "तुमची सहकारी संस्था जतन केलेली कामाची नोंद तपासेल."],
  job: ["Choose a job", "काम चुनें", "काम निवडा"],
  jobOrder: ["Who got the job", "काम किसको मिला", "काम कोणाला मिळाले"],
  workHours: ["My work hours", "मेरे काम के घंटे", "माझे कामाचे तास"],
  skills: ["My skills", "मेरा हुनर", "माझे कौशल्य"],
  coop: ["Another cooperative", "दूसरी सहकारी संस्था", "दुसरी सहकारी संस्था"],
  savedRecord: ["Saved job record", "काम का जतन किया रिकॉर्ड", "कामाची जतन केलेली नोंद"],
  checkSent: ["Request sent. Your cooperative will check this job.", "अनुरोध भेजा गया। आपकी सहकारी संस्था इस काम की जांच करेगी।", "विनंती पाठवली. तुमची सहकारी संस्था हे काम तपासेल."],
  checks: ["Your job checks", "आपकी जांच की स्थिति", "तुमच्या तपासणीची स्थिती"],
  received: ["Request received", "अनुरोध मिला", "विनंती मिळाली"],
  checked: ["Job record checked", "काम का रिकॉर्ड जांचा गया", "कामाची नोंद तपासली"],
  confirmed: ["The rule was followed", "नियम का पालन हुआ", "नियम पाळला गेला"],
  violation: ["A mistake was found", "गलती मिली", "चूक आढळली"],
  humanReview: ["A person will review this", "व्यक्ति जांच करेगा", "व्यक्ती तपासणी करेल"],
  remedied: ["Action recorded", "कार्रवाई दर्ज हुई", "कारवाई नोंदवली"],
  closed: ["Closed", "बंद", "बंद"],
  response: ["Cooperative reply", "सहकारी संस्था का जवाब", "सहकारी संस्थेचे उत्तर"],
  nextCheck: ["Waiting for the cooperative to check the job.", "सहकारी संस्था की जांच का इंतज़ार है।", "सहकारी संस्थेच्या तपासणीची वाट पाहत आहे."],
  helpIntro: ["What do you need help with?", "किस बात में मदद चाहिए?", "कशासाठी मदत हवी आहे?"],
  helpNote: ["Choose a problem. Your cooperative will receive your request.", "परेशानी चुनें। आपका अनुरोध सहकारी संस्था को जाएगा।", "अडचण निवडा. तुमची विनंती सहकारी संस्थेला जाईल."],
  relatedJob: ["Which job is this about?", "यह किस काम के बारे में है?", "हे कोणत्या कामाबद्दल आहे?"],
  general: ["Not about one job", "किसी एक काम के बारे में नहीं", "एका कामाबद्दल नाही"],
  describeHelp: ["For example: I have not received my pay.", "जैसे: मुझे मेरे पैसे नहीं मिले।", "उदा. माझे पैसे मिळाले नाहीत."],
  helpSent: ["Request sent. You can follow it below.", "अनुरोध भेजा गया। नीचे उसकी स्थिति देखें।", "विनंती पाठवली. खाली तिची स्थिती पहा."],
  requests: ["Your help requests", "आपके मदद के अनुरोध", "तुमच्या मदतीच्या विनंत्या"],
  noRequests: ["You have no help requests yet.", "अभी मदद का कोई अनुरोध नहीं है।", "अजून मदतीची विनंती नाही."],
  updated: ["Update added", "नई जानकारी जोड़ी गई", "नवीन माहिती जोडली"],
  addInfo: ["Add more information", "और जानकारी जोड़ें", "अधिक माहिती जोडा"],
  sendInfo: ["Send information", "जानकारी भेजें", "माहिती पाठवा"],
  helpStatus: ["The cooperative has received this request.", "सहकारी संस्था को यह अनुरोध मिल गया है।", "सहकारी संस्थेला ही विनंती मिळाली आहे."],
  ideasIntro: ["What could make work better?", "काम कैसे बेहतर हो सकता है?", "काम आणखी चांगले कसे होईल?"],
  ideasNote: ["Share one idea in your own words. Members can discuss it.", "अपने शब्दों में एक सुझाव दें। सदस्य उस पर बात कर सकते हैं।", "तुमच्या शब्दांत एक कल्पना सांगा. सदस्य त्यावर चर्चा करू शकतात."],
  ideaAbout: ["What is your idea about?", "सुझाव किस बारे में है?", "कल्पना कशाबद्दल आहे?"],
  payIdea: ["Better pay", "बेहतर भुगतान", "चांगला मोबदला"],
  jobsIdea: ["Sharing jobs", "काम बांटना", "काम वाटप"],
  safetyIdea: ["Safer work", "सुरक्षित काम", "सुरक्षित काम"],
  scopeIdea: ["Extra work and charges", "अतिरिक्त काम और पैसे", "अतिरिक्त काम आणि पैसे"],
  accessIdea: ["Getting more work", "ज़्यादा काम मिलना", "अधिक काम मिळणे"],
  ideaWords: ["Tell us your idea", "अपना सुझाव बताएं", "तुमची कल्पना सांगा"],
  ideaHint: ["For example: Please allow more rest between jobs.", "जैसे: दो कामों के बीच आराम के लिए ज़्यादा समय दें।", "उदा. दोन कामांमध्ये विश्रांतीसाठी अधिक वेळ द्या."],
  ideaLength: ["Write a short sentence (at least 10 characters).", "एक छोटा वाक्य लिखें (कम से कम 10 अक्षर)।", "एक लहान वाक्य लिहा (किमान 10 अक्षरे)."],
  sendIdea: ["Send my idea", "मेरा सुझाव भेजें", "माझी कल्पना पाठवा"],
  ideaSent: ["Idea sent. You can follow it below.", "सुझाव भेजा गया। नीचे उसकी स्थिति देखें।", "कल्पना पाठवली. खाली तिची स्थिती पहा."],
  myIdeas: ["Your ideas", "आपके सुझाव", "तुमच्या कल्पना"],
  noIdeas: ["No ideas sent yet.", "अभी कोई सुझाव नहीं भेजा।", "अजून कल्पना पाठवली नाही."],
  sent: ["Sent", "भेजा गया", "पाठवली"],
  reading: ["Being reviewed", "विचार हो रहा है", "विचार सुरू आहे"],
  acceptedIdea: ["Chosen for discussion", "चर्चा के लिए चुना गया", "चर्चेसाठी निवडली"],
  declinedIdea: ["Not taken forward", "आगे नहीं बढ़ाया गया", "पुढे नेली नाही"],
  ideaProcess: ["Sending an idea does not change the rules. Members must review and vote first.", "सुझाव भेजने से नियम नहीं बदलते। पहले सदस्य जांचते हैं और वोट देते हैं।", "कल्पना पाठवल्याने नियम बदलत नाहीत. आधी सदस्य तपासतात आणि मत देतात."],
  moneyIntro: ["See what you have earned and where it came from.", "देखें कितनी कमाई हुई और किस काम से हुई।", "किती कमाई झाली आणि कोणत्या कामातून झाली ते पहा."],
  moneyTotal: ["Total recorded earnings", "दर्ज कुल कमाई", "नोंदवलेली एकूण कमाई"],
  seePayments: ["See payments", "भुगतान देखें", "देयके पहा"],
  demoMoney: ["Demo amounts: sample history plus payments recorded in this demo.", "डेमो राशि: पुराने नमूने और इस डेमो में दर्ज भुगतान।", "डेमो रक्कम: जुने नमुने आणि या डेमोत नोंदवलेली देयके."],
  paidJobs: ["Paid jobs", "भुगतान वाले काम", "पैसे मिळालेली कामे"],
  cancelMoney: ["Pay for cancelled jobs", "रद्द कामों के पैसे", "रद्द कामांचे पैसे"],
  payments: ["Recent payments", "हाल के भुगतान", "अलीकडची देयके"],
  workPayment: ["Payment for {service}", "{service} के पैसे", "{service}चे पैसे"],
  cancellationPayment: ["Pay for a cancelled job", "रद्द काम के पैसे", "रद्द कामाचे पैसे"],
  sample: ["Sample record", "नमूना रिकॉर्ड", "नमुना नोंद"],
  live: ["Recorded in this demo", "इस डेमो में दर्ज", "या डेमोत नोंदवलेले"],
  noPayments: ["No payments recorded yet.", "अभी कोई भुगतान दर्ज नहीं है।", "अजून देयकाची नोंद नाही."],
  allPayments: ["See all payments", "सभी भुगतान देखें", "सर्व देयके पहा"],
  breakdown: ["Where my money came from", "मेरी कमाई कहाँ से हुई", "माझी कमाई कुठून झाली"],
  completedWork: ["Completed work", "पूरा हुआ काम", "पूर्ण झालेले काम"],
  unpaid: ["Jobs not paid yet", "जिन कामों के पैसे बाकी हैं", "पैसे बाकी असलेली कामे"],
  unpaidNote: ["These jobs are not included in your earnings yet.", "इन कामों के पैसे अभी कुल कमाई में नहीं जुड़े हैं।", "या कामांचे पैसे अजून एकूण कमाईत जोडलेले नाहीत."],
  votesIntro: ["Help decide our work rules.", "हमारे काम के नियम तय करने में भाग लें।", "आपल्या कामाचे नियम ठरवण्यात भाग घ्या."],
  rulesChange: ["A change to our work rules", "हमारे काम के नियमों में बदलाव", "आपल्या कामाच्या नियमांत बदल"],
  votesNote: ["Read the change. Then choose yes or no. Each member has one vote.", "बदलाव पढ़ें। फिर हाँ या नहीं चुनें। हर सदस्य का एक वोट है।", "बदल वाचा. मग हो किंवा नाही निवडा. प्रत्येक सदस्याचे एक मत आहे."],
  noVote: ["No vote is open right now.", "अभी वोट देने के लिए कोई प्रस्ताव नहीं है।", "सध्या मत देण्यासाठी प्रस्ताव नाही."],
  now: ["Now", "अभी", "आता"],
  ifApproved: ["If members approve", "सदस्य मंज़ूर करें तो", "सदस्यांनी मंजूर केल्यास"],
  minPay: ["Minimum pay for new jobs", "नए काम का न्यूनतम भुगतान", "नवीन कामाचा किमान मोबदला"],
  payIncrease: ["The minimum pay for a new job would rise by ₹{amount}.", "नए काम का न्यूनतम भुगतान ₹{amount} बढ़ेगा।", "नवीन कामाचा किमान मोबदला ₹{amount} वाढेल."],
  paySame: ["The minimum pay would stay the same.", "न्यूनतम भुगतान उतना ही रहेगा।", "किमान मोबदला तसाच राहील."],
  payDecrease: ["The proposed minimum pay is ₹{amount} lower. Review this carefully.", "प्रस्तावित न्यूनतम भुगतान ₹{amount} कम है। ध्यान से देखें।", "सुचवलेला किमान मोबदला ₹{amount} कमी आहे. काळजीपूर्वक पहा."],
  pastUnchanged: ["This is a proposal. It will not change money or job records from the past.", "यह प्रस्ताव है। पिछले भुगतान और काम के रिकॉर्ड नहीं बदलेंगे।", "हा प्रस्ताव आहे. आधीचे पैसे आणि कामाच्या नोंदी बदलणार नाहीत."],
  understood: ["I understand. Show voting", "मैं समझ गया/गई। वोट दिखाएं", "मला समजले. मतदान दाखवा"],
  choice: ["Do you agree with this change?", "क्या आप इस बदलाव से सहमत हैं?", "तुम्ही या बदलाशी सहमत आहात का?"],
  yes: ["Yes, I agree", "हाँ, मैं सहमत हूँ", "हो, मी सहमत आहे"],
  no: ["No, I disagree", "नहीं, मैं सहमत नहीं हूँ", "नाही, मी सहमत नाही"],
  whyNo: ["Why do you disagree?", "आप सहमत क्यों नहीं हैं?", "तुम्ही सहमत का नाही?"],
  whyNoHint: ["Tell members your reason in a few words.", "कुछ शब्दों में सदस्यों को कारण बताएं।", "काही शब्दांत सदस्यांना कारण सांगा."],
  confirmYes: ["Confirm my yes vote", "मेरा हाँ वोट दर्ज करें", "माझे हो मत नोंदवा"],
  confirmNo: ["Confirm my no vote", "मेरा नहीं वोट दर्ज करें", "माझे नाही मत नोंदवा"],
  voteRecorded: ["Your vote is recorded", "आपका वोट दर्ज है", "तुमचे मत नोंदवले आहे"],
  voteOnce: ["You have voted once. Your answer is saved.", "आपने एक बार वोट दिया है। आपका जवाब जतन है।", "तुम्ही एकदा मत दिले आहे. तुमचे उत्तर जतन आहे."],
  participation: ["{count} members have voted. At least 9 must take part and 7 must agree before this rule can start.", "{count} सदस्यों ने वोट दिया। नियम शुरू होने से पहले कम से कम 9 सदस्य वोट दें और 7 सहमत हों।", "{count} सदस्यांनी मत दिले. नियम सुरू होण्याआधी किमान 9 सदस्यांनी मत द्यावे आणि 7 जण सहमत असावेत."],
  voteResult: ["{count} members voted: {yes} agreed and {no} disagreed.", "{count} सदस्यों ने वोट दिया: {yes} सहमत और {no} असहमत।", "{count} सदस्यांनी मत दिले: {yes} सहमत आणि {no} असहमत."],
  voteSent: ["Your vote is saved.", "आपका वोट जतन है।", "तुमचे मत जतन आहे."],
  readyVote: ["You can now choose yes or no.", "अब हाँ या नहीं चुन सकते हैं।", "आता हो किंवा नाही निवडू शकता."],
  ruleActive: ["Members approved this rule. It is now in use.", "सदस्यों ने नियम मंज़ूर किया। यह अब लागू है।", "सदस्यांनी नियम मंजूर केला. आता तो वापरात आहे."],
  beforeChange: ["Before the change", "बदलाव से पहले", "बदलाआधी"],
  approvedRule: ["Approved rule", "मंज़ूर नियम", "मंजूर नियम"],
  voteClosed: ["Voting has ended for this proposal.", "इस प्रस्ताव पर मतदान खत्म हुआ।", "या प्रस्तावाचे मतदान संपले."],
  moreVote: ["Full proposal and vote count", "पूरा प्रस्ताव और वोट की गिनती", "पूर्ण प्रस्ताव आणि मतांची संख्या"],
  waitChange: ["Extra customer wait allowed when sharing work: {before} minutes now, {after} minutes if approved.", "काम बांटने के लिए ग्राहक का अतिरिक्त इंतज़ार: अभी {before} मिनट, मंज़ूर होने पर {after} मिनट।", "काम वाटताना ग्राहकाला अतिरिक्त वाट पाहण्याची मर्यादा: आता {before} मिनिटे, मंजूर झाल्यास {after} मिनिटे."],
  electrician: ["Electrical work", "बिजली का काम", "विजेचे काम"],
  plumbing: ["Plumbing", "नल का काम", "नळाचे काम"],
  cleaning: ["Cleaning", "सफाई", "साफसफाई"],
  appliance: ["Appliance repair", "उपकरण की मरम्मत", "उपकरण दुरुस्ती"],
  carpentry: ["Carpentry", "बढ़ई का काम", "सुतारकाम"],
  jobWork: ["Service work", "सेवा का काम", "सेवेचे काम"],
} as const;

export type WorkerCopyKey = keyof typeof phrases;
export function workerText(locale: Locale, key: WorkerCopyKey, params: Record<string, string | number> = {}) {
  const text: string = phrases[key][locale === "hi" ? 1 : locale === "mr" ? 2 : 0];
  return text.replace(/\{(\w+)\}/g, (_, name: string) => String(params[name] ?? `{${name}}`));
}
export function workerService(locale: Locale, service: string) {
  return workerText(locale, ["electrician", "plumbing", "cleaning", "appliance", "carpentry"].includes(service) ? service as WorkerCopyKey : "jobWork");
}
export function workerPayExample(locale: Locale, example: { service: string; currentPay: number; proposedPay: number } | undefined, floor: number) {
  const money = (value: number) => `₹${value.toLocaleString("en-IN")}`;
  const serviceForms: Record<string, WorkerCopyKey> = { electrician: "exampleElectrician", plumbing: "examplePlumbing",
    cleaning: "exampleCleaning", appliance: "exampleAppliance", carpentry: "exampleCarpentry" };
  return example ? workerText(locale, example.currentPay === example.proposedPay ? "simpleJobSame" : "simpleJobChange", {
    service: workerText(locale, serviceForms[example.service] ?? "exampleService"), before: money(example.currentPay), after: money(example.proposedPay),
  }) : workerText(locale, "simpleNoJob", { amount: money(floor) });
}
export function workerStatus(locale: Locale, status: string) {
  const keys: Record<string, WorkerCopyKey> = {
    open: "received", responded: "updated", closed: "closed", submitted: "sent",
    "under-review": "reading", accepted: "acceptedIdea", declined: "declinedIdea",
    replayed: "checked", confirmed: "confirmed", violation: "violation",
    "human-review": "humanReview", remedied: "remedied", upheld: "violation", dismissed: "confirmed",
  };
  return workerText(locale, keys[status] ?? "reading");
}
